---
title: "R Notebook"
output: html_notebook
---

Generate weights 

```{r}
library(tidyverse)
library(sf)
library(raster)
library(exactextractr)
library(here)
library(autumn)
```


## Identify geographic regions 

```{r}
shapefile <- sf::read_sf(here("data/weighting/geography/rdc_zones-de-sante"))

results_ns <- readxl::read_xlsx(here("data/clean_data/2023-09-08/network_survey_2023-08-16.xlsx"), sheet = "main_networksurvival") %>% 
  mutate(screening_check == "yes")

deaths <- readxl::read_xlsx("~/Downloads/Tool1b_Clean_2023-06-30.xlsx", sheet = "deaths")

kalemie_shapefile <- shapefile %>% 
  filter(PROVINCE == "Tanganyika" & Nom == "Nyunzu")

nyunzu_shapefile <- shapefile %>% 
  filter(PROVINCE == "Tanganyika" & Nom == "Nyemba")

nyemba_shapefile <- shapefile %>% 
  filter(PROVINCE == "Tanganyika" & Nom == "Kalemie")
```


```{r}
data <- sf::read_sf("~/Downloads/rdc_aires-de-sante")

# Filter data for the specific province
filtered_data <- data %>% 
  filter(Province == "Tanganyika")

# Create a new variable to identify whether each ZS should be colored or grayed out
filtered_data <- filtered_data %>% 
  mutate(color_group = if_else(ZS %in% c("Kalemie", "Nyemba", "Nyunzu"), as.character(ZS), "Other"))

filtered_data %>% 
  filter(ZS %in% "Nyunzu")
```




```{r}
# List all .tif files in the folder
tif_files <- list.files(here("data/weighting/geography/world_pop_rasters/"), pattern = "\\.tif$", full.names = TRUE)

# List of shapefiles
shapefiles <- list(
  Kalemie = kalemie_shapefile,
  Nyunzu = nyunzu_shapefile,
  Nyemba = nyemba_shapefile
)

# Initialize an empty list to store results
results_list <- list()

# Loop over each .tif file
for (tif_file in tif_files) {
  imported_raster <- raster(tif_file)
  
  # Loop over each shapefile
  for (zone in names(shapefiles)) {
    shape <- shapefiles[[zone]]
    result <- exactextractr::exact_extract(imported_raster, shape, 'sum')
    
    # Extract gender and number from file name
    file_base_name <- basename(tif_file)
    gender <- str_extract(file_base_name, "_[mf]_")
    gender <- gsub("_", "", gender)
    number <- str_extract(file_base_name, "_\\d+_")
    number <- as.numeric(gsub("_", "", number))
    
    # Add to the list
    new_row <- data.frame(
      file_name = file_base_name,
      gender = gender,
      number = number,
      sum_value = sum(unlist(result)),
      zone_de_sante = zone
    )
    results_list[[length(results_list) + 1]] <- new_row
  }
}

# Combine all the data frames in the list into one data frame
results_df <- bind_rows(results_list)

```

```{r}
results_df %>% 
  group_by(zone_de_sante) %>% 
  summarize(sum(sum_value))
```

```{r}
results_df <- results_df %>% 
  mutate(age_class = case_when(
   number %in% c(20) ~ "[18,25)",
   number %in% c(25, 30) ~ "[25,35)",
   number %in% c(35, 40) ~ "[35, 45)",
   number %in% c(45, 50) ~ "[45, 55)",
   number %in% c(55, 60) ~ "[55, 65)",
   number %in% c(65, 70, 75, 80) ~ "[65, 100]"
  )) %>% 
  filter(!is.na(age_class))
```


```{r}
# Calculate marginal percentages
age_count <- results_df %>%
  group_by(age_class, zone_de_sante) %>%
  summarise(count = sum(sum_value)) %>% 
  mutate(covar = "age_class") %>% 
  rename(value = age_class) %>% 
  group_by(zone_de_sante) %>% 
  mutate(perc = count / sum(count))

gender_count <- results_df %>%
  group_by(gender, zone_de_sante) %>%
  summarise(count = sum(sum_value)) %>% 
  mutate(covar = "gender") %>% 
  rename(value = gender) %>% 
  group_by(zone_de_sante) %>% 
  mutate(perc = count / sum(count))

margin_pop <- bind_rows(age_count, gender_count) %>% 
  ungroup() %>% 
  dplyr::select(variable = covar, level = value, proportion = perc, zone_de_sante)



```


```{r}
results_ns <- results_ns %>% 
  filter(!is.na(ki_sex)) %>% 
  mutate(age_class = case_when(
    ki_age %in% c(18:24) ~ "[18,25)",
    ki_age %in% c(25:34) ~ "[25,35)",
    ki_age %in% c(33:44) ~ "[35, 45)",
    ki_age %in% c(45:54) ~ "[45, 55)",
    ki_age %in% c(55:64) ~ "[55, 65)",
    ki_age %in% c(65:100) ~ "[65, 100]"
  )) %>% 
  mutate(gender = ki_sex)
  

results_ns %>% filter(!is.na(sex))
```


```{r}
# Kalemie
margin_pop_kalemie <- margin_pop %>% 
  filter(zone_de_sante == "Kalemie") %>%
  mutate(proportion = round(proportion, 3)) %>% 
  dplyr::select(-zone_de_sante)

results_ns_kalemie <- results_ns %>% 
  filter(zone_de_sante_name == "Kalemie") %>% 
  harvest(margin_pop_kalemie)

# Nyunzu
margin_pop_nyunzu <- margin_pop %>% 
  filter(zone_de_sante == "Nyunzu") %>%
  mutate(proportion = round(proportion, 3)) %>% 
  dplyr::select(-zone_de_sante)

results_ns_nyunzu <- results_ns %>% 
  filter(zone_de_sante_name == "Nyunzu") %>% 
  harvest(margin_pop_nyunzu)

# Nyemba
margin_pop_nyemba <- margin_pop %>% 
  filter(zone_de_sante == "Nyemba") %>%
  mutate(proportion = round(proportion, 3)) %>% 
  dplyr::select(-zone_de_sante)

results_ns_nyemba <- results_ns %>% 
  filter(zone_de_sante_name == "Nyemba") %>% 
  harvest(margin_pop_nyemba)

# Combine all into one DataFrame
respondent_data <- bind_rows(results_ns_kalemie, results_ns_nyunzu, results_ns_nyemba)

```



```{r}
respondent_data %>% 
  ggplot(aes(x = weights)) + 
  geom_histogram(binwidth = 0.15) + 
  theme_cowplot() + 
  xlim(0, 5)
  
  
```
```{r}
respondent_data %>% 
  group_by(gender, age_class) %>% 
  summarize(mean(weights), mean(deaths_num_total), n = n())
```

```{r}
weights <- respondent_data %>% 
  dplyr::select(uuid_ki, weights)
```


```{r}
deaths_weighted <- deaths %>% 
  inner_join(weights, by = c("uuid_ki4" = "uuid_ki"))
```


```{r}
write_csv(deaths_weighted, here("data/clean_data/casey_files/deaths_weighted.csv"))

```

