---
title: "Generate weights - raking"
author: "Casey Breen" 
---

Generate weights - estimation code 

```{r}
## library packages 
library(here)
source(here("code", "helpers.R"))

## read in weighting targets 
weighting_targets <- read_csv(here("data/weighting/weighting_targets.csv"))

## read in weighting targets 
weighting_targets_micro <- read_csv(here("data/weighting/hh_weighting_micro_df.csv"))

## read in data 
survey_df <- read_csv(here("data/data_clean/quota_sample_survey.csv")) 

## read in death df 
death_df <- read_csv(here("data/data_clean/quota_sample_deaths.csv"))
```

## Marginal population totals 

```{r}
# Define a function to calculate marginal percentages
calculate_marginal_percentage <- function(data, group_var) {
  data %>%
    group_by(!!sym(group_var), health_zone) %>%
    summarise(count = sum(sum_value)) %>%
    mutate(covar = group_var) %>%
    rename(value = !!sym(group_var)) %>%
    group_by(health_zone) %>%
    mutate(perc = count / sum(count))
}

# Apply the function for age_class and gender
age_count <- calculate_marginal_percentage(weighting_targets, "age_class")
gender_count <- calculate_marginal_percentage(weighting_targets, "gender")


# Combine the results
margin_pop <- bind_rows(age_count, gender_count) %>%
  ungroup() %>%
  dplyr::select(variable = covar, level = value, proportion = perc, health_zone)
```

```{r}
## read survey df 
survey_df <- survey_df %>% 
  mutate(age_class = case_when(
    ki_age %in% c(18:24) ~ "[18,25)",
    ki_age %in% c(25:34) ~ "[25,35)",
    ki_age %in% c(33:44) ~ "[35,45)",
    ki_age %in% c(45:54) ~ "[45,55)",
    ki_age %in% c(55:64) ~ "[55,65)",
    ki_age %in% c(65:100) ~ "[65,100]"
  )) %>% 
  mutate(gender = ki_sex) %>% 
  mutate(age_gender = paste0(gender, " | ", age_class))
```

<!-- ## construct raking weights  -->

<!-- ```{r} -->
<!-- ##  -->
<!-- weighting_raking_targets <- read_csv(here("data", "weighting", "weighting_raking_targets.csv")) -->

<!-- survey_df_weighted <- networksurvival::generate_raking_weights(weighting_targets = weighting_raking_targets, survey_df = survey_df)  -->

<!-- ## survey df weighted                                                                                                                                                    -->
<!-- survey_df_weighted <- survey_df_weighted %>%  -->
<!--   mutate(weight_raking = weights) %>%  -->
<!--   dplyr::select(-weights) -->

<!-- ``` -->

## poststratification weights 

Use pre-written poststratification function 

```{r}
## poststratification weights 
survey_df_weighted <- networksurvival::generate_poststrat_weights(weighting_targets = weighting_targets, survey_df = survey_df) 
```

## IPW weights 


```{r}
## poststratification weights 
survey_df_weighted <- networksurvival::generate_ipw_weights(weighting_targets = weighting_targets_micro, survey_df = survey_df_weighted) 
```



## weights 

```{r}
## weights 
weights <- survey_df_weighted %>% 
  dplyr::select(uuid_ki, weight_poststrat, weight_ipw)

## death df 
death_weighted <- death_df %>% 
  inner_join(weights, by = c("uuid_ki"))
```


## write csv files  

```{r}
## write csv 
write_csv(death_weighted, here("data", "data_clean", "quota_sample_deaths.csv"))
write_csv(survey_df_weighted, here("data", "data_clean", "quota_sample_survey.csv"))
```




<!-- ```{r} -->
<!-- # Define a function to calculate marginal percentages -->
<!-- calculate_marginal_percentage <- function(data, group_var) { -->
<!--   data %>% -->
<!--     group_by(!!sym(group_var), health_zone) %>% -->
<!--     count() %>% -->
<!--     mutate(covar = group_var) %>% -->
<!--     rename(value = !!sym(group_var)) %>% -->
<!--     group_by(health_zone) %>% -->
<!--     mutate(perc = count / sum(count)) -->
<!-- } -->


<!-- calculate_marginal_percentage <- function(data, group_var) { -->
<!--   data %>% -->
<!--     group_by(!!sym(group_var), health_zone) %>% -->
<!--     count() %>% -->
<!--     group_by(health_zone) %>% -->
<!--     mutate(proportion = n / sum(n)) %>% -->
<!--     ungroup() %>% -->
<!--     select(health_zone, level = !!sym(group_var), proportion) %>% -->
<!--     mutate(variable = group_var) # Directly assign the name of group_var as a string -->
<!-- } -->



<!-- # Apply the function for age_class and gender -->
<!-- age_count_survey <- calculate_marginal_percentage(survey_df_weighted, group_var = "age_class") -->
<!-- gender_count_survey <- calculate_marginal_percentage(survey_df_weighted, "gender") -->
<!-- age_u5_count <- calculate_marginal_percentage(survey_df_weighted, "age_u5_count")  -->
<!-- count_house_material <- calculate_marginal_percentage(survey_df_weighted, "age_5_18_count") -->
<!-- age_5_18_count <- calculate_marginal_percentage(survey_df_weighted, "age_18plus_count") -->
<!-- hh_size_categorical <- calculate_marginal_percentage(survey_df_weighted, "hh_size_categorical")  -->
<!-- wealth_score_categorical <- calculate_marginal_percentage(survey_df_weighted, "wealth_score_categorical")  -->

<!-- # Combine the results -->
<!-- margin_pop_survey <- bind_rows(age_count_survey, gender_count_survey, -->
<!--                                age_u5_count, count_house_material, age_5_18_count, hh_size_categorical, wealth_score_categorical ) -->

<!-- ## margin comparison -->
<!-- margin_comparison <- margin_pop_survey %>% -->
<!--   left_join(weighting_raking_targets %>% rename(proportion_pop = proportion), by = c("variable", "level", "health_zone")) -->

<!-- comparison_plot <- margin_comparison %>%  -->
<!--   mutate(variable = case_when( -->
<!--     variable == "age_18plus_count" ~ "HH 18+", -->
<!--     variable == "age_5_18_count"   ~ "HH 5-18", -->
<!--     variable == "age_u5_count" ~ "HH U5", -->
<!--     variable == "hh_size_categorical" ~ "HH Size", -->
<!--     variable == "wealth_score_categorical" ~ "Wealth Score", -->
<!--     variable == "gender" ~ "Gender", -->
<!--     variable == "age_class" ~ "Age" -->
<!--   )) %>%  -->
<!--   filter(health_zone != "Nyemba") %>% -->
<!--   ggplot() + -->
<!--   geom_segment(aes(xend = proportion, x = proportion_pop, y = level, yend = level), -->
<!--                color = 'black', -->
<!--                alpha = 0.5) + -->
<!--   geom_point(size = 1.5, aes(x = proportion, y = level, color = "Sample")) +  # Color inside aes -->
<!--   geom_point(size = 1.5, aes(x = proportion_pop, y = level, color = "Population")) +  # Color inside aes -->
<!--   facet_grid(variable ~ health_zone, scales = 'free_y', space = 'free_y', switch = 'y') + -->
<!--   labs(x = "Fraction") + -->
<!--   scale_color_manual(name = "", values = c("Sample" = "black", 'Population' = "red")) + -->
<!--   scale_x_continuous(labels = scales::percent_format(), n.breaks = 10) + -->
<!--   theme_bw() + -->
<!--   theme(legend.position = c(1, 1), # Top-right corner -->
<!--         legend.justification = c("right", "top"), # Anchor the legend at its top-right -->
<!--         legend.direction = 'vertical', -->
<!--         legend.margin = margin(t = 0, unit = 'cm'), -->
<!--         legend.box.background = element_rect(colour = "black"), -->
<!--         legend.title = element_blank()) -->

<!-- ggsave(plot = comparison_plot, filename = here("figures/margin_comparison.png"), width = 7, height = 9) -->
<!-- ``` -->



<!-- ```{r} -->
<!-- ## survey df weighted  -->
<!-- survey_df_weighted %>%  -->
<!--   ggplot(aes(x = weight_poststrat)) +  -->
<!--   geom_histogram(binwidth = 0.3, color = "black", fill = "grey") +  -->
<!--   theme_cowplot() +  -->
<!--   scale_x_continuous(breaks = seq(0, 9, by = 0.5), limits = c(0, 9)) # Add tick marks every 0.05  -->

<!-- ## survey df weighted  -->
<!-- survey_df_weighted %>%  -->
<!--   ggplot(aes(x = weight_raking)) +  -->
<!--   geom_histogram(binwidth = 0.3, color = "black", fill = "grey") +  -->
<!--   theme_cowplot() +  -->
<!--   scale_x_continuous(breaks = seq(0, , by = 0.5), limits = c(0, 9)) # Add tick marks every 0.05  -->


<!-- # Assuming survey_df_weighted is your data frame with the columns weight_poststrat and weight_raking -->
<!-- weight_distribution_plot <- survey_df_weighted %>% -->
<!--   pivot_longer(cols = c(weight_poststrat, weight_raking),  -->
<!--                names_to = "weight_type",  -->
<!--                values_to = "weight") %>% -->
<!--   mutate(weight_type = case_when( -->
<!--     weight_type == "weight_poststrat" ~ "Poststratification", -->
<!--     weight_type == "weight_raking" ~ "Raking")) %>%  -->
<!--   ggplot(aes(x = weight)) +  -->
<!--   geom_histogram(binwidth = 0.2, color = "black", fill = "grey") +  -->
<!--   facet_wrap(~weight_type,  -->
<!--              scales = "free_x", -->
<!--              ncol = 1) + -->
<!--   theme_cowplot() +  -->
<!--   scale_x_continuous(breaks = seq(0, 9, by = 0.5), limits = c(0, 9)) -->


<!-- ggsave(plot = weight_distribution_plot, filename = here("figures/weight_distn.png"), width = 6, height = 6) -->
<!-- ``` -->
