---
title: "Calculate Household Mortality Estimates"
author: Casey Breen
---

Summary: Estimate HH mortality rate 


```{r}
## Library package 
library(tidyverse)
library(srvyr)
library(cowplot)


## read in dataset 
final_hh_data <- read_csv(here("data", "clean_data", "hh_survey_data_clean.csv")) 
weight_HH <- readxl::read_xlsx(path = here("data", "clean_data", "weight_pop.xlsx"))
```


```{r}
## survey mortality period 
srvey_mortality_fullperiod_ns <- as_survey_design(final_hh_data,
                                  strata = "health_zone",
                                  weights = "weights")

age_specific_cdr <- srvey_mortality_fullperiod_ns %>% 
  group_by(age_group) %>% 
  summarise(x = survey_ratio(numerator =  death * 10000,
                             denominator = person_time_new,
                             vartype = "ci",
                             deff = "replace")) %>%
  mutate(across(where(is.numeric), ~round(., 2))) %>%
  mutate(variable = "cmr")

# Assuming age_specific_cdr is your data frame
# First plot for one part of the data
plot1 <- age_specific_cdr %>%
  filter(x < 2.6) %>% 
  ggplot(aes(x = age_group, y = x, ymin = x_low, ymax = x_upp)) +
  geom_pointrange() +
  theme_cowplot() +
  labs(x = "                              Age Group",
       y = "Crude Death Rate",
       title = "Age-specific CDR - HH Survey") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Second plot for the other part of the data
plot2 <- age_specific_cdr %>%
  filter(x > 2.6) %>% 
  ggplot(aes(x = age_group, y = x, ymin = x_low, ymax = x_upp)) +
  geom_pointrange() +
  theme_cowplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(x = "", y = NULL, title = "") 

# Combine the two plots
combined_plot <- plot_grid(plot1, plot2, align = 'v', ncol = 2, rel_widths = c(2, 1))

# Print the combined plot
combined_plot
```


```{r}
death_df %>% 
  filter(death_uuid != "WVOVEC") %>%
  filter(!is.na(death_hh_or_neighbour)) %>% 
  mutate(cat = case_when(
    death_hh_or_neighbour == "neighbour" ~ "Neighbor (not kin)",
    death_hh_or_neighbour == "neither" ~ "Kin (not neighbor or HH)",
    death_hh_or_neighbour == "own_hh" ~ "Own HH"
    )) %>% 
  mutate(month = lubridate::floor_date(as_date(final_date_death), unit = "months")) %>% 
  group_by(month, cat) %>% 
  summarize(deaths = n()) %>% 
  ggplot(aes(x = month, y = deaths)) + 
  geom_point() + 
  geom_line() + 
  theme_cowplot() + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  labs(x = "", y = "death counts", title = "Household survey - deaths reported by month") + 
    facet_wrap(~cat, ncol = 1) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        panel.grid.major = element_line(color = "grey80", size = 0.1)
        ) 
```



```{r}
## survey mortality period 
srvey_mortality_fullperiod_ns <- as_survey_design(final_hh_data,
                                  strata = "health_zone",
                                  weights = "weights")
 
## hh crude 
hh_crude_zone_de_sante <- srvey_mortality_fullperiod_ns %>%
  group_by(health_zone) %>% 
  summarise(x = survey_ratio(numerator =  death * 10000,
                             denominator = person_time_new,
                             vartype = "ci",
                             deff = "replace")) %>%
  mutate(across(where(is.numeric), ~round(., 2))) %>%
  mutate(variable = "cmr")

# Plot
ggplot(hh_crude_zone_de_sante, aes(x = health_zone, y = x)) +
  geom_errorbar(aes(ymin = x_low, ymax = x_upp), width = 0.1) + # Pointrange for the error bars
  geom_point(size = 10, shape = 21, fill = "white", color = "black", stroke = .7) + # Bubble-like points
  geom_text(aes(label = round(x, 2)), vjust = 0.3, size = 3.1) + # Numbers above bubbles
  theme_cowplot() +
  labs(x = "Administrative Unit", y = "CDR (Deaths / 10,000 person days)", title = "Crude Death Rate Estimates") +
  theme(legend.position = "none", axis.text.x = element_text(angle = 45, hjust = 1)) + 
  ylim(0, 1.1) 
```


```{r}
final_hh_data <- final_hh_data %>% 
  mutate(hh_id = sub("_[^_]*$", "", id)) 
```


```{r}
final_hh_data <- final_hh_data %>% 
  left_join(hh_df %>% 
              select(education_level, uuid_col), by = c("hh_id" = "uuid_col"))
```

```{r}
## survey mortality period 
srvey_mortality_fullperiod_ns <- as_survey_design(final_hh_data,
                                  strata = "health_zone",
                                  weights = "weights")


education_disparities <- srvey_mortality_fullperiod_ns %>%
  group_by(education_level) %>% 
  summarise(x = survey_ratio(numerator =  death * 10000,
                             denominator = person_time_new,
                             vartype = "ci",
                             deff = "replace")) %>%
  mutate(across(where(is.numeric), ~round(., 2))) %>%
  mutate(variable = "cmr")


# Factor the variable column to control the order on the x-axis
education_disparities$education_level <- factor(education_disparities$education_level, levels = c("none", "primary", "lower_secondary", "upper_secondary", "superior", "dontknow"))

# Plot
education_disparities %>% 
  filter(education_level != "dontknow") %>% 
ggplot(aes(x = education_level, y = x, ymin = x_low, ymax = x_upp)) +
  geom_pointrange() +
  theme_cowplot() +
  labs(title = "Point Range Plot by Education Level",
       x = "Education Level",
       y = "Value") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  ylim(0, 1.2)
```



