---
title: "Construct weights"
author: Casey B
---


Summary: Construct weights 


ages: (18–24, 25–34, 35–44, 45–54, 55–64, 65+), gender (female and male), and health zone (Nyunzu and Kalemie)


```{r}
# Load required libraries
library(tidyverse)
library(caret) # For pre-processing
library(psych) # For PCA
library(here)
library(autumn)
```



```{r}
## read in survey df
survey_df_nonprob <- read_csv(here("data", "clean_data", "survey_df_cleaned_weighted_dec3_2023.csv")) %>% 
  filter(zone_de_sante_name != "Nyunzu")

hh_df <- readxl::read_xlsx(here("data", "raw_data", "2023-09-08", "mortality_survey_clean_2023-09-08.xlsx"), sheet = "household") %>% 
  filter(consent == "yes") 

roster_df <- readxl::read_xlsx(here("data", "raw_data", "2023-09-08", "mortality_survey_clean_2023-09-08.xlsx"), sheet = "roster") 
```


```{r}
## roster df 
roster_df <- roster_df %>% 
  left_join(hh_df %>% dplyr::select(zone_de_sante, zone_de_sante_name, uuid_col), 
            by = c('_submission__uuid' = 'uuid_col')) 

## roster df drop ages 
roster_df <- roster_df %>% 
  mutate(age_years = as.numeric(age_years)) %>% 
  filter(age_years >= 18)

## roster df gender 
roster_df <- roster_df %>% 
  mutate(gender = sex_roster) %>% 
   mutate(age_class = case_when(
    age_years %in% c(18:24) ~ "[18,25)",
    age_years %in% c(25:34) ~ "[25,35)",
    age_years %in% c(33:44) ~ "[35,45)",
    age_years %in% c(45:54) ~ "[45,55)",
    age_years %in% c(55:64) ~ "[55,65)",
    age_years %in% c(65:100) ~ "[65,100]"
  ))
```



```{r}
## clean up hh df 
hh_df <- hh_df %>% 
  mutate(age = as.numeric(age_repondant)) %>% 
  mutate(gender = sexe_repondant) %>% 
  mutate(education_level = case_when(
    education_level == "dontknow" ~ "none",
    TRUE ~  education_level
  )) %>% 
   mutate(age_class = case_when(
    age %in% c(18:24) ~ "[18,25)",
    age %in% c(25:34) ~ "[25,35)",
    age %in% c(33:44) ~ "[35,45)",
    age %in% c(45:54) ~ "[45,55)",
    age %in% c(55:64) ~ "[55,65)",
    age %in% c(65:100) ~ "[65,100]"
  )) %>% 
  mutate(gender = case_when(
    gender == "f'" ~ "f",
    TRUE ~ gender
  ))


# Adjust the function for recategorization with lowercase variable names and without dashes
recategorize_livelihood <- function(livelihood) {
  case_when(
    livelihood %in% c('employed_agriculture', 'self_agriculture', 'sell_anim_prod') ~ 'agriculture',
    livelihood %in% c('daily_labour_non', 'daily_labour_skilled', 'unskilled', 'skilled') ~ 'labor',
    livelihood %in% c('professional', 'clerical') ~ 'professional',
    livelihood %in% c('sales', 'trader') ~ 'sales',
    livelihood %in% c('domestic', 'other', 'not_working') ~ 'domestic_other',
    TRUE ~ 'no_response_misc' # Including 'noresponse', 'army', and any others not explicitly listed
  )
}

# Apply the recategorization to the data frames and count with variable names in lowercase
survey_df_nonprob <- survey_df_nonprob %>%
  mutate(livelihood = recategorize_livelihood(livelihood)) 

hh_df <- hh_df %>%
  mutate(livelihood = recategorize_livelihood(livelihood)) 
## clean up 

```



```{r}
# Bind the two datasets together for PCA calculations
combined_data_for_pca <- bind_rows(
  hh_df %>% dplyr::select(material_house, cooking_fuel, bed, radio),
  survey_df_nonprob %>% dplyr::select(material_house, cooking_fuel, bed, radio)
)

# Encode binary variables for combined dataset
combined_data_for_pca <- combined_data_for_pca %>%
  mutate(bed = ifelse(bed == "yes", 1, 0),
         radio = ifelse(radio == "yes", 1, 0))

# One-hot encode categorical variables for combined dataset
dummy_model_combined <- dummyVars("~ .", data = combined_data_for_pca)
combined_data_transformed <- predict(dummy_model_combined, combined_data_for_pca)

# Scale/Normalize combined data
combined_data_scaled <- scale(combined_data_transformed)

# Run PCA on combined data
pca_result_combined <- prcomp(combined_data_scaled, center = TRUE, scale. = TRUE)

pca_score_df <- tibble(pca_score = pca_result_combined$x[,1]) %>% 
  mutate(wealth_quantile = cut_number(pca_score, 5)) %>%
  mutate(wealth_quantile_bin = as.numeric(fct_rev(wealth_quantile))) 

# Now split the PCA scores back to the original datasets
hh_df <- hh_df %>%
  bind_cols(pca = pca_score_df[1:nrow(hh_df),])

survey_df_nonprob <- survey_df_nonprob %>%
    bind_cols(pca = pca_score_df[(nrow(hh_df) + 1):(nrow(hh_df) + nrow(survey_df_nonprob)),])

# Rest of your original code to apply wealth quantiles and summarize
hh_df %>% 
  group_by(zone_de_sante) %>% 
  summarize(mean(wealth_quantile_bin))

survey_df_nonprob %>% 
    group_by(zone_de_sante) %>% 
  summarize(mean(wealth_quantile_bin))

```
746601

```{r}
# Define a function to calculate marginal percentages
calculate_marginal_percentage <- function(data, group_var) {
  data %>%
    group_by(!!sym(group_var), zone_de_sante) %>%
    summarise(count = n()) %>%
    mutate(covar = group_var) %>%
    rename(value = !!sym(group_var)) %>%
    group_by(zone_de_sante) %>%
    mutate(perc = count / sum(count))
}

# Apply the function for age_class and gender
age_count <- calculate_marginal_percentage(roster_df, "age_class")
gender_count <- calculate_marginal_percentage(roster_df, "gender")
wealth_count <- calculate_marginal_percentage(hh_df, "wealth_quantile_bin") %>% 
  mutate(value = as.character(value))

# Combine the results
margin_pop_hh <- bind_rows(age_count, gender_count, wealth_count) %>%
  ungroup() %>%
  dplyr::select(variable = covar, level = value, proportion = perc, zone_de_sante)
```





```{r}
# Kalemie
margin_pop_kalemie <- margin_pop_hh %>% 
  filter(zone_de_sante == "746101") %>%
 # mutate(proportion = round(proportion, 4)) %>% 
  dplyr::select(-zone_de_sante) %>% 
  as.data.frame()

results_ns_kalemie <- survey_df_nonprob %>% 
  filter(zone_de_sante == 746101)  %>% 
  harvest(margin_pop_kalemie)

# Nyunzu
margin_pop_nyunzu <- margin_pop_hh %>% 
  filter(zone_de_sante == "746102") %>%
  dplyr::select(-zone_de_sante)

results_ns_nyunzu <- survey_df_nonprob %>% 
  filter(zone_de_sante == 746102) %>% 
  harvest(margin_pop_nyunzu)


# Combine all into one DataFrame
survey_df_weighted <- bind_rows(results_ns_kalemie, results_ns_nyunzu) 

## survey df weighted 
survey_df_weighted <- survey_df_weighted %>% 
  rename(weight_hh_sample = weights)
```


```{r}
## weights 
weights <- survey_df_weighted %>% 
  dplyr::select(uuid_ki, weight_hh_sample)

death_df <- read_csv(here("data", "clean_data", "death_df_cleaned_weighted_dec3_2023.csv"))

## death df 
death_weighted <- death_df %>% 
  inner_join(weights, by = c("uuid_ki"))

death_df <- write_csv(death_weighted, here("data", "clean_data", "death_df_cleaned_weighted_feb18_2023.csv"))

```



```{r}
survey_df_weighted %>% 
  group_by(age_class, gender, wealth_quantile_bin) %>% 
  summarize(mean(weight_hh_sample))
```




```{r}
# Apply the function for age_class and gender
age_count_survey <- calculate_marginal_percentage(survey_df_weighted, group_var = "age_class")
gender_count_survey <- calculate_marginal_percentage(survey_df_weighted, "gender")
wealth_count_survey <- calculate_marginal_percentage(survey_df_weighted, "wealth_quantile_bin") %>% 
  mutate(value = as.character(value))

# Combine the results
margin_pop_survey <- bind_rows(age_count_survey, gender_count_survey, wealth_count_survey) %>%
  ungroup() %>%
  dplyr::select(variable = covar, level = value, proportion = perc, zone_de_sante)

## margin comparison
margin_comparison <- margin_pop_survey %>%
  left_join(margin_pop_hh %>% mutate(zone_de_sante = as.numeric(zone_de_sante)) %>% rename(proportion_pop = proportion), by = c("variable", "level", "zone_de_sante"))

margin_comparison %>% 
  mutate(health_zone = case_when(
    zone_de_sante == "746101" ~ "Kalemie",
    zone_de_sante == "746102" ~ "Nyemba"
  )) %>% 
  ggplot() +
  geom_segment(aes(xend = proportion, x = proportion_pop, y = level, yend = level),
               color = 'black',
               alpha = 0.5) +
  geom_point(size = 1.5, aes(x = proportion, y = level, color = "Sample")) +  # Color inside aes
  geom_point(size = 1.5, aes(x = proportion_pop, y = level, color = "Population")) +  # Color inside aes
  facet_grid(variable ~ health_zone, scales = 'free_y', space = 'free_y', switch = 'y') +
  labs(x = "Fraction of sample") +
  scale_color_manual(name = "", values = c("Sample" = "black", 'Population' = "red")) +
  scale_x_continuous(labels = scales::percent_format(), n.breaks = 10) +
  theme_bw() +
  theme(legend.position = c(1, 1), # Top-right corner
        legend.justification = c("right", "top"), # Anchor the legend at its top-right
        legend.direction = 'vertical',
        legend.margin = margin(t = 0, unit = 'cm'),
        legend.box.background = element_rect(colour = "black"),
        legend.title = element_blank())
```


