---
title: "Estimate mortality network method"
author: Casey Breen
---

```{r}
## library packages 
library(here)
source(here("code", "helpers.R"))

## read in datasets
hh_sample_mortality_long <- read_csv(here("data", "data_clean", "hh_sample_mortality_long.csv"))
hh_sample_deaths <- read_csv(here("data", "data_clean", "hh_sample_deaths.csv"))
hh_sample_neighbors <- read_csv(here("data", "data_clean", "hh_sample_neighbors.csv"))
hh_sample_respondent <- read_csv(here("data", "data_clean", "hh_sample_respondent.csv"))

## read in survey df
quota_sample_survey <- read_csv(here("data", "data_clean", "quota_sample_survey.csv")) 
quota_sample_deaths <- read_csv(here("data", "data_clean", "quota_sample_deaths.csv"))

## read in weighting targets 
weighting_targets <- read_csv(here("data", "weighting", "weighting_targets.csv"))

## read in weighting targets 
weighting_targets_raking <- read_csv(here("data", "weighting", "weighting_raking_targets.csv"))

```



```{r}
hh_sample_respondent <- hh_sample_respondent %>% 
  mutate(health_zone = health_zone,
         gender = case_when(
           sexe_repondant == "f" ~ "f",
           sexe_repondant == "m" ~ "m",
           sexe_repondant == "f'" ~ "f"
          ),
         age_class = case_when(
    age_repondant %in% c(18:24) ~ "[18,25)",
    age_repondant %in% c(25:34) ~ "[25,35)",
    age_repondant %in% c(33:44) ~ "[35,45)",
    age_repondant %in% c(45:54) ~ "[45,55)",
    age_repondant %in% c(55:64) ~ "[55,65)",
    age_repondant %in% c(65:100) ~ "[65,100]"
  )) %>% 
  mutate(age_gender = paste0(gender, " | ", age_class))


hh_sample_respondent <- hh_sample_respondent %>% 
  mutate(num_total_kin = coalesce(a_total_kin, b_total_kin)) %>% 
  mutate(num_total_kin = as.numeric(num_total_kin)) %>% 
  mutate(a_sum_neighbours = coalesce(a_sum_neighbours, b_sum_neighbours)) %>% 
  mutate(num_total_hh_neighbour = as.numeric(a_sum_neighbours) + as.numeric(num_hh)) %>% 
  mutate(num_total_hh = as.numeric(num_hh)) %>% 
  mutate(start_month = 1,
         weight_poststrat = 1) %>% 
  mutate(uuid_ki = uuid_col)

hh_sample_deaths <- hh_sample_deaths %>%  
  mutate(`death_relationship/family` = is_kin,
         `death_relationship/neighbour` = is_neighbour,
         `death_relationship/household` = is_hh) %>% 
  mutate(uuid_ki = `_submission__uuid`) %>% 
  mutate(weight_poststrat = 1)
```

```{r}
## estimate point estimates 
cdr_pooled_hz_point <- networksurvival::compute_cdr_comprehensive(death_df = hh_sample_deaths,
                                                                  survey_df = hh_sample_respondent,
                                                                  weight_col = "weight_poststrat",
                                                                  subpopulation = "health_zone",
                                                                  bootstrap = NA)

cdr_pooled_hz_boostrap <- networksurvival::compute_cdr_comprehensive(death_df = hh_sample_deaths,
                                                                     survey_df = hh_sample_respondent, 
                                                                     weight_col = "weight_poststrat",
                                                                     subpopulation = "health_zone", bootstrap = 100)

## zone de sante - Uncertainty Intervals
cdr_pooled_hz_uncertainty <- cdr_pooled_hz_boostrap %>% 
  group_by(health_zone, type, weights) %>% 
  summarize(death_rate_lower = quantile(death_rate, 0.025),
            death_rate_upper = quantile(death_rate, 0.975)) 

## perform join 
cdr_pooled_hz_point_uncertainty <- inner_join(cdr_pooled_hz_point, cdr_pooled_hz_uncertainty, by = c("type", "health_zone", "weights")) %>% 
  mutate(survey = "hh")

## visualize results 
cdr_pooled_heath_zones_plot <- cdr_pooled_hz_point_uncertainty %>% 
  filter(weights == "poststrat") %>% 
#   filter(type != "household") %>% 
  ggplot(aes(x = health_zone, color = type, shape = type, y = death_rate, ymin = death_rate_lower, ymax = death_rate_upper)) + 
  geom_pointrange( position = position_dodge(.25), size = 1, fill = "white") +
  scale_shape_manual(values = c(21, 22, 23, 24)) +
  scale_color_viridis_d() +  
  ylim(0, 1.2) + 
  theme_cowplot() + 
  theme(legend.position = "bottom", legend.title = element_blank()) + 
  labs(x = "Zone de Sante",
       y = "Estimated Average Daily Crude Death Rate",
       labs = "HH Survey Estimates")

ggsave(plot = cdr_pooled_heath_zones_plot, filename = here("figures", "cdr_pooled_heath_zones_plot.png"), width = 7, height = 5)
```





```{r}
## estimate point estimates 
cdr_pooled_hz_point_nonprob <- networksurvival::compute_cdr_comprehensive(death_df = quota_sample_deaths,
                                                                          survey_df = quota_sample_survey,
                                                                          weight_col = "weight_raking",
                                                                          subpopulation = "health_zone",
                                                                          bootstrap = NA)

cdr_pooled_hz_boostrap_nonprob <- networksurvival::compute_cdr_comprehensive(death_df = quota_sample_deaths,
                                                                             survey_df = quota_sample_survey, 
                                                                             weight_col = "weight_raking",
                                                                             weight_targets = weighting_targets_raking,
                                                                             weight_type = "raking", 
                                                                             subpopulation = "health_zone", 
                                                                             bootstrap = 100)

## zone de sante - Uncertainty Intervals
cdr_pooled_hz_uncertainty_nonprob <- cdr_pooled_hz_boostrap_nonprob %>% 
  group_by(health_zone, type, weights) %>% 
  summarize(death_rate_lower = quantile(death_rate, 0.025),
            death_rate_upper = quantile(death_rate, 0.975)) 

## perform join 
cdr_pooled_hz_point_uncertainty_nonprob <- inner_join(cdr_pooled_hz_point_nonprob, cdr_pooled_hz_uncertainty_nonprob, by = c("type", "health_zone", "weights")) %>% 
  mutate(survey = "quota")

## visualize results 
cdr_pooled_heath_zones_plot <- cdr_pooled_hz_point_uncertainty_nonprob %>% 
  filter(weights == "poststrat") %>% 
#   filter(type != "household") %>% 
  ggplot(aes(x = health_zone, color = type, shape = type, y = death_rate, ymin = death_rate_lower, ymax = death_rate_upper)) + 
  geom_pointrange( position = position_dodge(.25), size = 1, fill = "white") +
  scale_shape_manual(values = c(21, 22, 23, 24)) +
  scale_color_viridis_d() +  
  ylim(0, 1.2) + 
  theme_cowplot() + 
  theme(legend.position = "bottom", legend.title = element_blank()) + 
  labs(x = "Zone de Sante",
       y = "Estimated Average Daily Crude Death Rate",
       labs = "HH Survey Estimates") 
```


```{r}
final_results_plot <- cdr_pooled_hz_point_uncertainty_nonprob %>%
  bind_rows(cdr_pooled_hz_point_uncertainty) %>%
  mutate(survey = case_when(
    survey == "hh" ~ "Household",
    survey == "quota" ~ "Quota"
  )) %>%
  filter(health_zone %in% c("Kalemie", "Nyunzu")) %>%
  filter(weights == "poststrat") %>%
  # Assuming 'type' needs to be ordered as specified; adjust as necessary
  mutate(type = factor(type, levels = c("household", "kin", "neighbor", "blended"))) %>%
  ggplot(aes(x = type, color = survey, shape = survey, y = death_rate, ymin = death_rate_lower, ymax = death_rate_upper)) +
  geom_pointrange(position = position_dodge(.3), size = 1, fill = "white") +
  scale_shape_manual(values = c(21, 22, 23, 24)) +
  ggsci::scale_color_lancet() +
  ylim(0, 1.2) +
  theme_cowplot() +
  theme(legend.position = "bottom", legend.title = element_blank()) +
  labs(x = "Type of Survey",
       y = "Estimated Average Daily Crude Death Rate",
       title = "") +  # Changed 'labs' to 'title'
  facet_wrap(~health_zone, nrow = 2)



ggsave(plot = final_results_plot, filename = here("figures/main_comparison_plot.png"), height = 8, width = 6)
```

