---
title: Internal validity checks
author: Casey Breen
---

Internal validity checks and other robustness checks 


```{r}
library(tidyverse)
library(here)
library(boot)
library(cowplot)

cudb <- c("#49b7fc", "#ff7b00", "#17d898", "#ff0083", "#0015ff", "#e5d200", "#999999")
cud <- c("#D55E00", "#56B4E9", "#009E73", "#CC79A7", "#0072B2", "#E69F00", "#F0E442", "#999999")
```


## scratch 

```{r}
quota_sample_survey <- read_csv(here("data", "data_clean", "quota_sample_survey.csv")) # %>% filter(health_zone != "Nyunzu")
```



```{r}
# Define a function to compute the percent differences between brothers reporting connections to sisters and sisters reporting connections to brothers
boot_fn_siblings_percent_diff <- function(data, indices) {
  boot_data <- data[indices, ]
  
  # Calculate the percent difference between male respondents reporting sisters and female respondents reporting brothers for each weight type
  c(
    # Unweighted percent difference
    percent_diff_unweighted = (sum(boot_data$num_total_kin_sisters_over18[boot_data$gender == "m"]) - 
                               sum(boot_data$num_total_kin_brothers_over18[boot_data$gender == "f"])) /
                               ((sum(boot_data$num_total_kin_sisters_over18[boot_data$gender == "m"]) + 
                                 sum(boot_data$num_total_kin_brothers_over18[boot_data$gender == "f"])) / 2),
    
    # IPW percent difference
    percent_diff_ipw = (sum(boot_data$num_total_kin_sisters_over18[boot_data$gender == "m"] * boot_data$weight_ipw[boot_data$gender == "m"]) - 
                        sum(boot_data$num_total_kin_brothers_over18[boot_data$gender == "f"] * boot_data$weight_ipw[boot_data$gender == "f"])) /
                        ((sum(boot_data$num_total_kin_sisters_over18[boot_data$gender == "m"] * boot_data$weight_ipw[boot_data$gender == "m"]) + 
                          sum(boot_data$num_total_kin_brothers_over18[boot_data$gender == "f"] * boot_data$weight_ipw[boot_data$gender == "f"])) / 2),
    
    # Post-stratified percent difference
    percent_diff_poststrat = (sum(boot_data$num_total_kin_sisters_over18[boot_data$gender == "m"] * boot_data$weight_poststrat[boot_data$gender == "m"]) - 
                              sum(boot_data$num_total_kin_brothers_over18[boot_data$gender == "f"] * boot_data$weight_poststrat[boot_data$gender == "f"])) /
                              ((sum(boot_data$num_total_kin_sisters_over18[boot_data$gender == "m"] * boot_data$weight_poststrat[boot_data$gender == "m"]) + 
                                sum(boot_data$num_total_kin_brothers_over18[boot_data$gender == "f"] * boot_data$weight_poststrat[boot_data$gender == "f"])) / 2)
  )
}

# Apply bootstrapping to compute the percent differences
bootstrap_results_siblings_percent_diff <- quota_sample_survey %>%
  do({
    results <- boot(data = ., statistic = boot_fn_siblings_percent_diff, R = 1000)
    
    # Extract standard errors
    se_values <- apply(results$t, 2, sd)
    
    # Return the original percent differences (t0) and the corresponding standard errors (se_values)
    tibble(
      percent_diff_unweighted = results$t0[1],
      se_percent_diff_unweighted = se_values[1],
      
      percent_diff_ipw = results$t0[2],
      se_percent_diff_ipw = se_values[2],
      
      percent_diff_poststrat = results$t0[3],
      se_percent_diff_poststrat = se_values[3]
    )
  })

# Combine the estimates and standard errors for easier plotting
summary_long_siblings_percent_diff <- bootstrap_results_siblings_percent_diff %>%
  # Pivot both the estimates and standard errors
  pivot_longer(cols = c(starts_with("percent_diff_"), starts_with("se_percent_diff_")),
               names_to = c(".value", "weight_type"),
               names_pattern = "(percent_diff|se_percent_diff)_(.*)",
               values_drop_na = TRUE)

# Map weight type to readable labels
summary_long_siblings_percent_diff <- summary_long_siblings_percent_diff %>%
  mutate(weight_type = case_when(
    weight_type == "unweighted" ~ "Unweighted",
    weight_type == "ipw" ~ "Inverse Probability",
    weight_type == "poststrat" ~ "Post-stratification"
  ))
```

```{r}
# Define a function to compute the percent differences for female reports of male cousins minus male reports of female cousins across all weight types
boot_fn_cousins_percent_diff <- function(data, indices) {
  boot_data <- data[indices, ]
  
  # Calculate percent differences between female respondents reporting male cousins and male respondents reporting female cousins
  c(
    # Unweighted percent difference
    percent_diff_unweighted = (sum(boot_data$num_total_kin_male_cousins_over18[boot_data$gender == "f"]) - 
                               sum(boot_data$num_total_kin_female_cousins_over18[boot_data$gender == "m"])) /
                               ((sum(boot_data$num_total_kin_male_cousins_over18[boot_data$gender == "f"]) + 
                                 sum(boot_data$num_total_kin_female_cousins_over18[boot_data$gender == "m"])) / 2),
    
    # IPW percent difference
    percent_diff_ipw = (sum(boot_data$num_total_kin_male_cousins_over18[boot_data$gender == "f"] * boot_data$weight_ipw[boot_data$gender == "f"]) - 
                        sum(boot_data$num_total_kin_female_cousins_over18[boot_data$gender == "m"] * boot_data$weight_ipw[boot_data$gender == "m"])) /
                        ((sum(boot_data$num_total_kin_male_cousins_over18[boot_data$gender == "f"] * boot_data$weight_ipw[boot_data$gender == "f"]) + 
                          sum(boot_data$num_total_kin_female_cousins_over18[boot_data$gender == "m"] * boot_data$weight_ipw[boot_data$gender == "m"])) / 2),
    
    # Post-stratified percent difference
    percent_diff_poststrat = (sum(boot_data$num_total_kin_male_cousins_over18[boot_data$gender == "f"] * boot_data$weight_poststrat[boot_data$gender == "f"]) - 
                              sum(boot_data$num_total_kin_female_cousins_over18[boot_data$gender == "m"] * boot_data$weight_poststrat[boot_data$gender == "m"])) /
                              ((sum(boot_data$num_total_kin_male_cousins_over18[boot_data$gender == "f"] * boot_data$weight_poststrat[boot_data$gender == "f"]) + 
                                sum(boot_data$num_total_kin_female_cousins_over18[boot_data$gender == "m"] * boot_data$weight_poststrat[boot_data$gender == "m"])) / 2)
  )
}

# Apply bootstrapping to calculate the percent differences by gender
bootstrap_results_cousins_percent_diff <- quota_sample_survey %>%
  do({
    results <- boot(data = ., statistic = boot_fn_cousins_percent_diff, R = 1000)
    
    # Extract standard errors
    se_values <- apply(results$t, 2, sd)
    
    # Return the original percent differences (t0) and the corresponding standard errors (se_values)
    tibble(
      percent_diff_unweighted = results$t0[1],
      se_percent_diff_unweighted = se_values[1],
      
      percent_diff_ipw = results$t0[2],
      se_percent_diff_ipw = se_values[2],
      
      percent_diff_poststrat = results$t0[3],
      se_percent_diff_poststrat = se_values[3]
    )
  })

# Combine the estimates and standard errors for easier plotting
summary_long_cousins_percent_diff <- bootstrap_results_cousins_percent_diff %>%
  # Pivot both the estimates and standard errors
  pivot_longer(cols = c(starts_with("percent_diff_"), starts_with("se_percent_diff_")),
               names_to = c(".value", "weight_type"),
               names_pattern = "(percent_diff|se_percent_diff)_(.*)",
               values_drop_na = TRUE)

# Map weight type to readable labels
summary_long_cousins_percent_diff <- summary_long_cousins_percent_diff %>%
  mutate(weight_type = case_when(
    weight_type == "unweighted" ~ "Unweighted",
    weight_type == "ipw" ~ "Inverse Probability",
    weight_type == "poststrat" ~ "Post-stratification"
  ))

```

```{r}
# Define a function to compute percent differences for parents and children over 18 across all weight types
boot_fn_parents_children_percent <- function(data, indices) {
  boot_data <- data[indices, ]
  
  # Compute the sums for parents and children
  total_parents_unweighted <- sum(boot_data$num_total_kin_fathers_over18) + sum(boot_data$num_total_kin_mothers_over18)
  total_children_unweighted <- sum(boot_data$num_total_kin_male_child_over18) + sum(boot_data$num_total_kin_female_child_over18)
  
  total_parents_ipw <- sum(boot_data$num_total_kin_fathers_over18 * boot_data$weight_ipw) + sum(boot_data$num_total_kin_mothers_over18 * boot_data$weight_ipw)
  total_children_ipw <- sum(boot_data$num_total_kin_male_child_over18 * boot_data$weight_ipw) + sum(boot_data$num_total_kin_female_child_over18 * boot_data$weight_ipw)
  
  total_parents_poststrat <- sum(boot_data$num_total_kin_fathers_over18 * boot_data$weight_poststrat) + sum(boot_data$num_total_kin_mothers_over18 * boot_data$weight_poststrat)
  total_children_poststrat <- sum(boot_data$num_total_kin_male_child_over18 * boot_data$weight_poststrat) + sum(boot_data$num_total_kin_female_child_over18 * boot_data$weight_poststrat)
  
  # Calculate percent differences
  c(
    percent_diff_unweighted = (total_parents_unweighted - total_children_unweighted) / ((total_parents_unweighted + total_children_unweighted) / 2) ,
    
    percent_diff_ipw = (total_parents_ipw - total_children_ipw) / ((total_parents_ipw + total_children_ipw) / 2) ,
    
    percent_diff_poststrat = (total_parents_poststrat - total_children_poststrat) / ((total_parents_poststrat + total_children_poststrat) / 2)
  )
}

# Apply bootstrapping
bootstrap_results_parents_children_percent <- quota_sample_survey %>%
  do({
    results <- boot(data = ., statistic = boot_fn_parents_children_percent, R = 1000)
    
    # Extract standard errors
    se_values <- apply(results$t, 2, sd)
    
    # Return the original estimates (t0) and the corresponding standard errors (se_values)
    tibble(
      percent_diff_unweighted = results$t0[1],
      se_percent_diff_unweighted = se_values[1],
      
      percent_diff_ipw = results$t0[2],
      se_percent_diff_ipw = se_values[2],
      
      percent_diff_poststrat = results$t0[3],
      se_percent_diff_poststrat = se_values[3]
    )
  })

# Combine the data to prepare for plotting
summary_long_parents_children_percent <- bootstrap_results_parents_children_percent %>%
  pivot_longer(cols = c(starts_with("percent_diff_")), 
               names_to = "weight_type", 
               values_to = "percent_diff") %>%
  pivot_longer(cols = starts_with("se_percent_diff_"),
               names_to = "se_weight_type",
               values_to = "se_percent_diff") %>%
  filter(gsub("se_", "", se_weight_type) == weight_type)

# Mapping weight type to readable labels
summary_long_parents_children_percent <- summary_long_parents_children_percent %>%
  mutate(weight_type = case_when(
    weight_type == "percent_diff_unweighted" ~ "Unweighted",
    weight_type == "percent_diff_ipw" ~ "Inverse Probability",
    weight_type == "percent_diff_poststrat" ~ "Post-stratification"
  ))

```

```{r}
# Combine the three datasets and label them
combined_summary <- bind_rows(
  summary_long_siblings_percent_diff %>% mutate(relationship = "Female reports to brothers - male reports to sisters"),
  summary_long_cousins_percent_diff %>% mutate(relationship = "Female reports to male cousins - male reports to female cousins"),
  summary_long_parents_children_percent %>% mutate(relationship = "Respondent reports to parents - respondent reports to children (18+)")
)

# Plot the combined data
combined_plot <- combined_summary %>%
  ggplot(aes(x = weight_type, y = percent_diff, ymin = percent_diff - 1.96 * se_percent_diff, ymax = percent_diff + 1.96 * se_percent_diff, color = relationship, shape = relationship)) +
  geom_pointrange(position = position_dodge(width = 0.2), size = 1) +
  labs(title = "",
       x = "",
       y = "Percent Difference",
       color = "Relationship Comparison",
       shape = "Relationship Comparison") +
  theme_cowplot() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black", size = 1) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits = c(-.50, .50)) +
  scale_color_manual(values = c("Female reports to brothers - male reports to sisters" = "#1b9e77",
                                "Female reports to male cousins - male reports to female cousins" = "#d95f02",
                                "Respondent reports to parents - respondent reports to children (18+)" = "#7570b3")) + 
    background_grid(minor = 'none')  + 
  theme(
    legend.position = "bottom",            # Places the legend at the bottom
    legend.direction = "vertical",       # Makes the legend horizontal
    legend.box = "vertical"            # Ensures the layout is horizontal
  )
# Plot the results
combined_plot

ggsave(combined_plot, filename = here("figures/internal_validity_checks.png"), width = 7, height = 5, dpi = 300, bg = "white") 
```
## proportion within groups 




```{r}
## household roster for ground truth 
household_sample_roster <- read_csv(here("data", "data_clean", "hh_sample_roster.csv"))  

household_sample_prop <- household_sample_roster %>% 
  filter(!is.na(calc_final_age_years)) %>% 
  mutate(age_group = case_when(
    calc_final_age_years < 5 ~ "Under 5",
    calc_final_age_years >= 5 & calc_final_age_years < 18 ~ "Under 18, over 5",
    calc_final_age_years >= 18 ~ "Over 18"
  )) %>% 
  count(age_group) %>%
  mutate(proportion = n / sum(n)) %>% 
  mutate(relation = "Probability, household")
```

```{r}
household_age_profile <- quota_sample_survey %>%
  summarise(
    under_5 = sum(num_total_hh_under5) / sum(num_total_hh),
    under_18 = sum(num_total_hh_under18) / sum(num_total_hh),
    over_18 = sum(num_total_hh_over18) / sum(num_total_hh)) %>% 
  mutate(relation = "household")

neighbor_age_profile <- quota_sample_survey %>%
  summarise(
    under_5 = sum(num_total_neighbour_under5) / sum(num_total_neighbour),
    under_18 = sum(num_total_neighbour_under18) / sum(num_total_neighbour),
    over_18 = sum(num_total_neighbour_over18) / sum(num_total_neighbour)) %>% 
  mutate(relation = "neighbor")

kin_age_profile <- quota_sample_survey %>% 
 summarise(
    under_5 = sum(num_total_kin_under5) / sum(num_total_kin),
    under_18 = sum(num_total_kin_under18) / sum(num_total_kin),
    over_18 = sum(num_total_kin_over18) / sum(num_total_kin)) %>% 
  mutate(relation = "kin") 

# Combine the two summaries into one data frame
combined_summary_unweighted <- bind_rows(household_age_profile, neighbor_age_profile, kin_age_profile)

# Pivot the data to longer format for easier plotting or further analysis
combined_summary_long_unweighted <- combined_summary_unweighted %>%
  pivot_longer(cols = c(under_5, under_18, over_18), names_to = "age_group", values_to = "proportion") %>% 
  mutate(relation = factor(relation, levels = c("neighbor", "household", "kin"))) %>% 
  mutate(age_group = case_when(
    age_group == "under_5" ~ "Under 5",
    age_group == "under_18" ~ "Under 18, over 5",
    age_group == "over_18" ~ "Over 18"
  ))%>% 
  bind_rows(household_sample_prop) %>% 
  mutate(relation = case_when(
    relation == "household" ~ "Quota, household",
    relation == "neighbor" ~ "Quota, neighbor",
    relation == "kin" ~ "Quota, kin",
    TRUE ~ relation))


quota_sample_prop_within_groups_unweighted <- ggplot(combined_summary_long_unweighted, aes(x = age_group, y = proportion, fill = relation, label = paste0(round(proportion * 100, 0), "%"))) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9), alpha = 0.6, color = "black") +
  geom_text(position = position_dodge(width = 0.9), vjust = -0.5) +  # Add text with dodge position
  labs(
    title = "Unweighted quota sample",
    x = "Age Group",
    y = "Proportion"
  ) +
  theme_cowplot() +
  scale_fill_manual(values = c("Quota, household" = "#1f77b4", "Quota, neighbor" = "#ff7f0e", "Quota, kin" = "darkgreen", "Probability, household" = "grey")) +  # Ensure that "kin" is quoted correctly
  theme(legend.position = "bottom", legend.title = element_blank()) + 
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits = c(0, .6))  # Format the y-axis as a percentage
```




```{r}
# Household age profile with weights
household_age_profile <- quota_sample_survey %>%
  summarise(
    under_5 = sum(num_total_hh_under5 * weight_ipw) / sum(num_total_hh * weight_ipw),
    under_18 = sum(num_total_hh_under18 * weight_ipw) / sum(num_total_hh * weight_ipw),
    over_18 = sum(num_total_hh_over18 * weight_ipw) / sum(num_total_hh * weight_ipw)
  ) %>% 
  mutate(relation = "household")

# Neighbor age profile with weights
neighbor_age_profile <- quota_sample_survey %>%
  summarise(
    under_5 = sum(num_total_neighbour_under5 * weight_ipw) / sum(num_total_neighbour * weight_ipw),
    under_18 = sum(num_total_neighbour_under18 * weight_ipw) / sum(num_total_neighbour * weight_ipw),
    over_18 = sum(num_total_neighbour_over18 * weight_ipw) / sum(num_total_neighbour * weight_ipw)
  ) %>% 
  mutate(relation = "neighbor")

# Kin age profile with weights
kin_age_profile <- quota_sample_survey %>% 
  summarise(
    under_5 = sum(num_total_kin_under5 * weight_ipw) / sum(num_total_kin * weight_ipw),
    under_18 = sum(num_total_kin_under18 * weight_ipw) / sum(num_total_kin * weight_ipw),
    over_18 = sum(num_total_kin_over18 * weight_ipw) / sum(num_total_kin * weight_ipw)
  ) %>% 
  mutate(relation = "kin")


# Combine the two summaries into one data frame
combined_summary <- bind_rows(household_age_profile, neighbor_age_profile, kin_age_profile)

# Pivot the data to longer format for easier plotting or further analysis
combined_summary_long <- combined_summary %>%
  pivot_longer(cols = c(under_5, under_18, over_18), names_to = "age_group", values_to = "proportion") %>% 
  mutate(relation = factor(relation, levels = c("neighbor", "household", "kin"))) %>% 
  mutate(age_group = case_when(
    age_group == "under_5" ~ "Under 5",
    age_group == "under_18" ~ "Under 18, over 5",
    age_group == "over_18" ~ "Over 18"
  )) %>% 
  bind_rows(household_sample_prop) %>% 
  mutate(relation = case_when(
    relation == "household" ~ "Quota, household",
    relation == "neighbor" ~ "Quota, neighbor",
    relation == "kin" ~ "Quota, kin",
    TRUE ~ relation))


quota_sample_prop_within_groups_weighted <- ggplot(combined_summary_long, aes(x = age_group, y = proportion, fill = relation, label = paste0(round(proportion * 100, 0), "%"))) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9), alpha = 0.6, color = "black") +
  geom_text(position = position_dodge(width = 0.9), vjust = -0.5) +  # Add text with dodge position
  labs(
    title = "IPW weighted quota sample",
    x = "Age Group",
    y = "Proportion"
  ) +
  theme_cowplot() +
  scale_fill_manual(values = c("Quota, household" = "#1f77b4", "Quota, neighbor" = "#ff7f0e", "Quota, kin" = "darkgreen", "Probability, household" = "grey")) +  # Ensure that "kin" is quoted correctly
  theme(legend.position = "bottom", legend.title = element_blank()) + 
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits = c(0, .6))  # Format the y-axis as a percentage


# Extract the legend from the unweighted plot
legend <- get_legend(quota_sample_prop_within_groups_unweighted + theme(legend.position = "bottom"))

# Remove the legend from both plots
quota_sample_prop_within_groups_unweighted <- quota_sample_prop_within_groups_unweighted + theme(legend.position = "none")
quota_sample_prop_within_groups_weighted <- quota_sample_prop_within_groups_weighted + theme(legend.position = "none")

# Combine the unweighted plot with the legend and the weighted plot without a legend
quota_sample_prop_within_groups_combined <- plot_grid(
  plot_grid(quota_sample_prop_within_groups_unweighted, quota_sample_prop_within_groups_weighted, ncol = 2, rel_heights = c(0.5, 0.5)),
  legend,
  nrow = 2,
  rel_heights = c(1, 0.1)
)

# Save the combined plot
ggsave(quota_sample_prop_within_groups_combined, filename = here("figures/age_profile_quota.png"), width = 12, height = 5, dpi = 300, bg = "white")
```





```{r}
household_sample_respondent <- read_csv(here("data", "data_clean", "hh_sample_respondent.csv"))

household_sample_respondent %>% 
  ungroup() %>% 
  summarize(
    num_total_neighbour_under5 = sum(coalesce(a_sum_neighbours_male_under5, 0) +
                                     coalesce(a_sum_neighbours_female_under5, 0) +
                                     coalesce(b_sum_neighbours_male_under5, 0) +
                                     coalesce(b_sum_neighbours_female_under5, 0)),
    
    num_total_neighbour_under18 = sum(coalesce(a_sum_neighbours_male_under18, 0) +
                                      coalesce(a_sum_neighbours_female_under18, 0) +
                                      coalesce(b_sum_neighbours_male_under18, 0) +
                                      coalesce(b_sum_neighbours_female_under18, 0)),
    
    num_total_neighbour_over18 = sum(coalesce(a_sum_neighbours_male_over18, 0) +
                                     coalesce(a_sum_neighbours_female_over18, 0) +
                                     coalesce(b_sum_neighbours_male_over18, 0) +
                                     coalesce(b_sum_neighbours_female_over18, 0))) %>% 
  mutate(id = 1) %>% 
  pivot_longer(-id) %>% 
  mutate(prop = value / sum(value))
```


```{r}
pyramid_df <- household_sample_roster %>% 
  count(sex_roster, age_years) 

# Create a population pyramid
pyramid_df %>%
  mutate(n = ifelse(sex_roster == "m", -n, n)) %>%  # Negative counts for males
  ggplot(aes(x = age_years, y = n, fill = sex_roster)) +
  geom_bar(stat = "identity", width = 0.9) +
  coord_flip() +
  scale_y_continuous(labels = abs) +  # Make the y-axis labels positive
  labs(title = "Population Pyramid",
       x = "Age",
       y = "Population Count") +
  scale_fill_manual(values = c("m" = "skyblue", "f" = "pink"),  # Adjust colors to match the data
                    labels = c("Male", "Female")) +  # Adjust the legend labels
  theme_minimal() +
  theme(legend.position = "bottom")
```








