---
title: "Distribution of network size figures"
author: Casey Breen
---

```{r}
## library packages 
library(here)
source(here("code", "helpers.R"))
```



```{r}
## read in survey df
quota_sample_survey <- read_csv(here("data", "data_clean", "quota_sample_survey.csv")) # %>% filter(health_zone != "Nyunzu")

quota_sample_survey <- quota_sample_survey %>%
  filter(!(start_month == as_date("2023-06-01") & health_zone == "Nyunzu"))
```


```{r}
quota_sample_survey <-  quota_sample_survey %>% 
  mutate(
    a_total_kin = a_male_child_total + a_female_child_total +
                  a_male_grandchild_total + a_female_grandchild_total +
                  a_sisters_total + a_brothers_total +
                  a_male_cousins_total + a_female_cousins_total +
                  a_parents_total + a_aunts_total +
                  a_uncles_total + a_grandfathers_total + a_grandmothers_total,
                  
    b_total_kin = b_male_child_total + b_female_child_total +
                  b_male_grandchild_total + b_female_grandchild_total +
                  b_sisters_total + b_brothers_total +
                  b_male_cousins_total + b_female_cousins_total +
                  b_parents_total + b_aunts_total +
                  b_uncles_total + b_grandfathers_total + b_grandmothers_total) %>% 
  mutate(a_num_deaths_neighbours = a_num_deaths_hh_neighbours - a_hh_deaths, 
         b_num_deaths_neighbours = b_num_deaths_hh_neighbours - b_hh_deaths)
```




```{r}
# Define the number of bootstrap iterations
n_bootstrap <- 1000

# Perform bootstrap sampling and calculate the means
bootstrap_df <- replicate(n_bootstrap, {
  # Resample the data with replacement
  sample_data <- sample_frac(quota_sample_survey, replace = TRUE)
  
  # Calculate the means for the resampled data
  sample_sums <- sample_data %>%
    summarize(
      a_kin_deaths = mean(a_num_deaths_kin, na.rm = TRUE),
      b_kin_deaths = mean(b_num_deaths_kin, na.rm = TRUE),
      a_hh_deaths = mean(a_hh_deaths, na.rm = TRUE),
      b_hh_deaths = mean(b_hh_deaths, na.rm = TRUE),
      a_neighbor_deaths = mean(a_num_deaths_neighbours, na.rm = TRUE), 
      b_neighbor_deaths = mean(b_num_deaths_neighbours, na.rm = TRUE)
    )
  
  # Return the summarized data frame
  return(sample_sums)
}, simplify = FALSE) %>% bind_rows()

# Calculate the means and standard deviations from the bootstrap results for each type
summary_results <- bootstrap_df %>%
  summarize(
    a_kin_deaths_mean = mean(a_kin_deaths),
    a_kin_deaths_sd = sd(a_kin_deaths),
    b_kin_deaths_mean = mean(b_kin_deaths),
    b_kin_deaths_sd = sd(b_kin_deaths),
    a_hh_deaths_mean = mean(a_hh_deaths),
    a_hh_deaths_sd = sd(a_hh_deaths),
    b_hh_deaths_mean = mean(b_hh_deaths),
    b_hh_deaths_sd = sd(b_hh_deaths),
    a_neighbor_deaths_mean = mean(a_neighbor_deaths),
    a_neighbor_deaths_sd = sd(a_neighbor_deaths),
    b_neighbor_deaths_mean = mean(b_neighbor_deaths),
    b_neighbor_deaths_sd = sd(b_neighbor_deaths)
  )

# Calculate the real means from the original data
real_sums <- quota_sample_survey %>%
  summarize(
    a_kin_sum_mean = mean(a_num_deaths_kin, na.rm = TRUE),
    b_kin_sum_mean = mean(b_num_deaths_kin, na.rm = TRUE),
    a_hh_sum_mean = mean(a_hh_deaths, na.rm = TRUE),
    b_hh_sum_mean = mean(b_hh_deaths, na.rm = TRUE),
    a_neighbor_sum_mean = mean(a_num_deaths_neighbours, na.rm = TRUE),
    b_neighbor_sum_mean = mean(b_num_deaths_neighbours, na.rm = TRUE)
  )

# Convert summary results to a data frame suitable for plotting for each type
plot_data <- tibble::tibble(
  type = rep(c("Kin", "Household", "Neighbors"), each = 2),  
  order = rep(c("First", "Second"), times = 3),             
  mean = c(real_sums$a_kin_sum_mean, real_sums$b_kin_sum_mean,
           real_sums$a_hh_sum_mean, real_sums$b_hh_sum_mean,
           real_sums$a_neighbor_sum_mean, real_sums$b_neighbor_sum_mean),
  sd = c(summary_results$a_kin_deaths_sd, summary_results$b_kin_deaths_sd,
         summary_results$a_hh_deaths_sd, summary_results$b_hh_deaths_sd,
         summary_results$a_neighbor_deaths_sd, summary_results$b_neighbor_deaths_sd)
)

# Plot means with error bars representing standard deviations for each type
survey_order_effects_plot_part1 <- plot_data %>% 
  ggplot(aes(x = type, y = mean, ymin = mean - 1.96 * sd, ymax = mean + 1.96 * sd, color = order)) +
  geom_pointrange(position = position_dodge(width = 0.2)) +  
  labs(
    title = "",
    y = "Mean deaths per interview",
    x = "",
    color = "Survey Module Order"
  ) +
  ggsci::scale_color_lancet() +  # Apply Lancet color scale
  coord_cartesian(ylim = c(0, .15)) +  # Set y-axis limits
  theme_cowplot() +  # Apply cowplot theme
  theme(legend.position =  "none")


#########################
# Plot round 2 
##########################

# Perform bootstrap sampling and calculate the sums
bootstrap_df <- replicate(n_bootstrap, {
  # Resample the data with replacement
  sample_data <- sample_frac(quota_sample_survey, replace = TRUE)
  
  # Calculate the means for the resampled data
  sample_data %>%
    summarize(
      a_kin_sum = mean(a_total_kin, na.rm = TRUE),
      b_kin_sum = mean(b_total_kin, na.rm = TRUE),
      a_hh_sum = mean(a_sum_neighbours, na.rm = TRUE),
      b_hh_sum = mean(b_sum_neighbours, na.rm = TRUE),
      a_household_sum = mean(a_tot_hh, na.rm = TRUE),
      b_household_sum = mean(b_tot_hh, na.rm = TRUE)
    )
}, simplify = FALSE) %>% bind_rows()

# Calculate the means and standard deviations from the bootstrap results
summary_results <- bootstrap_df %>%
  summarize(across(ends_with("sum"), list(mean = mean, sd = sd)))

# Calculate the real means from the original data
real_sums <- quota_sample_survey %>%
  summarize(
    a_kin_sum_mean = mean(a_total_kin, na.rm = TRUE),
    b_kin_sum_mean = mean(b_total_kin, na.rm = TRUE),
    a_hh_sum_mean = mean(a_sum_neighbours, na.rm = TRUE),
    b_hh_sum_mean = mean(b_sum_neighbours, na.rm = TRUE),
    a_household_sum_mean = mean(a_tot_hh, na.rm = TRUE),
    b_household_sum_mean = mean(b_tot_hh, na.rm = TRUE)
  )

# Convert summary results to a data frame suitable for plotting
plot_data_size <- tibble::tibble(
  type = rep(c("Kin", "Neighbors", "Household"), each = 2),  # Define types
  order = rep(c("First", "Second"), times = 3),                    # Define groups
  mean = c(real_sums$a_kin_sum_mean, real_sums$b_kin_sum_mean,
           real_sums$a_hh_sum_mean, real_sums$b_hh_sum_mean,
           real_sums$a_household_sum_mean, real_sums$b_household_sum_mean),
  sd = c(summary_results$a_kin_sum_sd, summary_results$b_kin_sum_sd,
         summary_results$a_hh_sum_sd, summary_results$b_hh_sum_sd,
         summary_results$a_household_sum_sd, summary_results$b_household_sum_sd)
)

# Plot means with error bars representing standard deviations
survey_order_effects_plot_part2 <- plot_data_size %>% 
  ggplot(aes(x = type, y = mean, ymin = mean - 1.96 * sd, ymax = mean + 1.96 * sd, color = order)) +
  geom_pointrange(position = position_dodge(width = 0.2)) +  # Add error bars with dodge and size for better visualization
  labs(
    title = "",
    y = "Network size",
    x = "",
    color = "Survey Module Order"
  ) +
  ggsci::scale_color_lancet() +  # Apply Lancet color scale
  theme_cowplot() +  # Apply cowplot theme
  theme(legend.position = "bottom") + 
  ylim(0, 31)

```


```{r}
survey_order_effects_plot <-  plot_grid(survey_order_effects_plot_part1, survey_order_effects_plot_part2, nrow = 2 )

# Save the plot
ggsave(survey_order_effects_plot, filename = here("figures", "survey_order_effects_plot.png"), width = 6, height = 7)
```




```{r}
quota_sample_survey <- quota_sample_survey %>% 
  mutate(num_total_neighbor = num_total_hh_neighbour - num_total_hh)

neighbor_sample <- quota_sample_survey %>% 
  ggplot(aes(x = num_total_neighbor)) + 
  geom_histogram(binwidth = 2, color = "black", fill = "grey") + 
  theme_cowplot() + 
  xlim(0, 100) + 
  geom_vline(xintercept = mean(quota_sample_survey$num_total_neighbor), color = "blue", linetype = "dashed", linewidth = 1) +
  labs(x = "Neighbor network size", 
       y = "n") + 
  annotate("text", x = 75, y = 200, label = paste0("Mean = ", round(mean(quota_sample_survey$num_total_neighbor), 1)), color = "blue") + 
    ylim(0, 720) 

hh_sample <- quota_sample_survey %>% 
  ggplot(aes(x = num_total_hh)) + 
  geom_histogram(binwidth = 2, color = "black", fill = "grey") +  
  theme_cowplot() + 
  xlim(0, 100) + 
  geom_vline(xintercept = mean(quota_sample_survey$num_total_hh), color = "blue", linetype = "dashed", linewidth = 1) +
    annotate("text", x = 75, y = 500, label = paste0("Mean = ", round(mean(quota_sample_survey$num_total_hh), 1)), color = "blue") +  # Corrected annotation function
  labs(x = "Household size",
       y = "n") + 
    ylim(0, 720) 

kin_sample <- quota_sample_survey %>% 
  ggplot(aes(x = num_total_kin)) + 
  geom_histogram(binwidth = 2, color = "black", fill = "grey") +  
  theme_cowplot() + 
  xlim(0, 100) + 
  geom_vline(xintercept = mean(quota_sample_survey$num_total_kin), color = "blue", linetype = "dashed", linewidth = 1) +
      annotate("text", x = 75, y = 200, label = paste0("Mean = ", round(mean(quota_sample_survey$num_total_kin), 1)), color = "blue") +  # Corrected annotation function
  labs(x = "Kin network size",
       y = "n") + 
    ylim(0, 720) 

plot_network_sizes <- plot_grid(hh_sample, kin_sample, neighbor_sample, ncol = 1)
```



```{r}
# Calculate means and standard errors
plot_data <- quota_sample_survey %>% 
  filter(!is.na(num_deaths_hh)) %>% 
  summarize(
    household_mean = mean(num_deaths_hh, na.rm = TRUE),
    household_se = sd(num_deaths_hh, na.rm = TRUE) / sqrt(n()),
    kin_mean = mean(num_deaths_kin, na.rm = TRUE),
    kin_se = sd(num_deaths_kin, na.rm = TRUE) / sqrt(n()),
    neighbor_mean = mean(num_deaths_neighbours, na.rm = TRUE),
    neighbor_se = sd(num_deaths_neighbours, na.rm = TRUE) / sqrt(n())
  ) %>% 
  pivot_longer(cols = everything(), 
               names_to = c("type", ".value"), 
               names_pattern = "(.*)_(.*)") %>% 
  mutate(type = factor(type, levels = c("neighbor", "kin", "household")))  # Arrange the y-axis order

# Plot with error bars using geom_pointrange
plot_death_reports <- ggplot(plot_data, aes(y = type, x = mean)) + 
  geom_pointrange(aes(xmin = mean - 1.96 * se, xmax = mean + 1.96 * se), size = 0.8, color = "darkred") +  # Add error bars
  xlim(0, 0.15) + 
  labs(x = "Avg. deaths per interview", y = "") + 
  theme_cowplot()
```


```{r}
plot_combined <- plot_grid(plot_network_sizes, plot_death_reports)

ggsave(plot_combined, filename = here("figures", "network_sizes_plot.png"), width = 7, height = 5)
```


