---
title: "Enumerator checks"
Author: Casey Breen
---

Summary: run checks on enumerator - exploratory 

```{r}
## library packages 
library(here)
source(here("code", "helpers.R"))

## read in survey df
quota_sample_survey <- read_csv(here("data", "data_clean", "quota_sample_survey.csv")) # %>% filter(health_zone != "Nyunzu")

## read in death df 
quota_sample_deaths <- read_csv(here("data", "data_clean", "quota_sample_deaths.csv")) # %>%  filter(health_zone != "Nyunzu")

quota_sample_deaths <- quota_sample_deaths %>% mutate(report_month = floor_date(death_date_dc, "month")) %>% filter(!(report_month == as_date("2023-06-01") & health_zone == "Nyunzu"))

## read in weighting targets 
weighting_targets_poststrat <- read_csv(here("data", "weighting", "weighting_targets.csv")) 

## read in weighting targets 
weighting_targets_raking <- read_csv(here("data", "weighting", "weighting_raking_targets.csv"))

## hh weighting micro df 
weight_targets_ipw <- read_csv(here("data/weighting/hh_weighting_micro_df.csv"))

## set seed
set.seed(1)
```

```{r}
quota_sample_survey %>% 
  filter(health_zone == "Nyunzu") %>% 
  group_by(enum, health_zone) %>% 
  summarize(mean(deaths_num_total), n()) 


quota_sample_survey %>% 
  filter(health_zone == "Nyunzu") %>% 
  group_by(enum, health_zone) %>% 
  summarize(mean(deaths_num_total), n()) 

```

```{r}
quota_sample_deaths %>% 
  count(death_enum, health_zone)  %>% 
  filter(health_zone == "Nyunzu")


quota_sample_deaths %>% 
  mutate(month = lubridate::floor_date(as_date(death_date_dc), "month")) %>% 
  count(month)
```

```{r}
quota_sample_survey %>% 
    mutate(month = lubridate::floor_date(as_date(start), "month")) %>% 
    filter(wealth_score == 4) %>% 
    group_by(month, health_zone) %>% 
    mutate(radio = case_when(
      radio == "no" ~ 0,
      TRUE ~ 1
    )) %>% 
    summarize(deaths = sum(deaths_num_total, na.rm = T), n(), mean(radio, na.rm = T)) %>% 
  ggplot(aes(x = month, y = deaths, color = health_zone)) + 
           geom_line() 


quota_sample_survey %>% 
  mutate(month = lubridate::floor_date(as_date(start), "month")) %>% 
  filter(enum == "team11") %>% 
  filter(health_zone == "Nyunzu") %>% 
  count(month, enum) 


quota_sample_survey %>% 
    filter(enum == "team11") %>% 
  filter(health_zone == "Nyunzu") %>% 
  summarize(min(start))

```



```{r}
quota_sample_survey %>% colnames()
```


```{r}
quota_sample_survey %>% 
  filter(health_zone == "Nyunzu") %>% 
  mutate(month = lubridate::floor_date(as_date(start), "month")) %>% 
  group_by(month) %>% 
      mutate(radio = case_when(
      radio == "no" ~ 0,
      TRUE ~ 1
    )) %>% 
  summarize(mean(weight_ipw), n(), mean(wealth_score))
```

