---
title: "Blended weights"
author: Casey Breen
---

Summary: Calculate blended weight 


```{r}
## library packages 
library(here)
source(here("code", "helpers.R"))
```


```{r}
## read in survey df
quota_sample_survey <- read_csv(here("data", "data_clean", "quota_sample_survey.csv")) 
quota_sample_survey <- quota_sample_survey %>%
  filter(enum != "team11")

## read in death df 
quota_sample_deaths <- read_csv(here("data", "data_clean", "quota_sample_deaths.csv")) 
quota_sample_deaths <- quota_sample_deaths %>% mutate(report_month = floor_date(death_date_dc, "month")) %>% 
  filter(death_enum != "team11")

## read in weighting targets 
weighting_targets_poststrat <- read_csv(here("data", "weighting", "weighting_targets.csv"))
weighting_targets_raking <- read_csv(here("data", "weighting", "weighting_raking_targets.csv"))
weight_targets_ipw <- read_csv(here("data/weighting/hh_weighting_micro_df.csv"))
```

## calculate weights 

```{r}
set.seed(1)

## bootstraps 
cdr_bootstrap_quota_ipw <- networksurvival::compute_cdr_comprehensive(death_df = quota_sample_deaths,
                                                                             survey_df = quota_sample_survey, 
                                                                             weight_col = "weight_ipw",
                                                                             weight_targets = weight_targets_ipw,
                                                                             weight_type = "ipw", 
                                                                             bootstrap = n_bootstrap_samples) 
```


```{r}
df <- cdr_bootstrap_quota_ipw %>% 
  filter(weights == "unweighted") %>% 
  filter(type != "blended") 

calculate_blended_weight_kin(df)
```





