---
title: "R Notebook"
author: Casey Breen
---



```{r, echo = F}
## library packages 
library(tidyverse)
library(data.table)

## read in survey 
formative_survey <- readxl::read_excel("../data/Dataset mortality.xlsm", sheet = 2)

## rename variables 
formative_survey <- formative_survey %>% 
  mutate(network1 = `11.1) Combien de personnes connaissez-vous à qui vous avez parlé en personne, au téléphone, ou par message ou messagerie instantanée au moins une fois par semaine (en moyenne) durant les 3 derniers mois ? Veuillez donner votre meilleure estimation`) %>% 
  mutate(network2 = `10.11) Combien de personnes connaissez-vous à qui vous avez parlé en personne, au téléphone, ou par message ou messagerie instantanée au moins une fois par semaine (en moyenne) durant les 3 derniers mois ? Veuillez donner votre meilleure estimation.`) %>% 
      mutate(deaths_12month = `12.2) Si oui, combien de personnes à qui vous avez souvent parlé sont décédées au cours des douze derniers mois ?`) %>% 
      mutate(deaths_6month = `12.3) Combien de personnes à qui vous avez souvent parlé sont décédées au cours des six derniers mois ?`) %>% 
  mutate(deaths_3month = `12.4) Combien de personnes à qui vous avez  souvent parlé sont décédées au cours des trois derniers mois ?`) %>% 
  mutate(deaths_1month = `12.5) Combien de personnes à qui vous avez  souvent parlé son décédées au cours du dernier mois ?`) %>% 
  mutate(network_talk_weekly = coalesce(network1, network2)) %>% 
  mutate(report_deaths = `12.1) Parmi les personnes avec qui vous parlez, connaissez-vous quelqu'un qui est décédé au cours des douze derniers mois ?`) %>% 
  mutate(job = `0.1.q) Quel est la profession de l'IC interrogé?` ) %>% 
  mutate(infants = `10.12) Parmi ces ${Q1_11} personnes, combien de petits enfants de moins de cinq ans ont-ils tous ?`,
         infants2 = `11.2) Parmi ces ${Q2_1} personnes, combien de petits enfants de moins de cinq ans ont-ils tous ?`,
         in_community1 = `10.13) Parmi ces ${Q1_11} personnes, combien d'entre elles vivent dans votre communauté ?`,
         in_community2 = `11.3) Parmi ces ${Q2_1} personnes, combien d'entre elles vivent dans votre communauté ?`,
         infants_in_community1 = `10.14) Parmi ces ${Q1_11_2} personnes dans votre communauté  ou de votre quartier, combien d'enfants de moins de 5 ans ont-ils tous ?`,
         infants_in_community2 = `11.4) Parmi ces ${Q2_1_2} personnes dans votre communauté ou de votre quartier, combien d'enfants de moins de 5 ans ont-ils tous ?`) %>% 
  mutate(infants =  coalesce(infants, infants2), 
         in_community = coalesce(in_community1, in_community2),
          infants_in_community = coalesce(infants_in_community1, infants_in_community2))

## recode variables 
formative_survey <- formative_survey %>% 
  filter(!is.na(report_deaths)) %>% 
  mutate(deaths_1month = case_when(
    report_deaths == "Oui" ~ deaths_1month,
    TRUE ~ 0),
    deaths_3month = case_when(
    report_deaths == "Oui" ~ deaths_3month,
    TRUE ~ 0),
    deaths_6month = case_when(
    report_deaths == "Oui" ~ deaths_6month,
    TRUE ~ 0),
    deaths_12month = case_when(
    report_deaths == "Oui" ~ deaths_12month,
    TRUE ~ 0))

```


```{r}
formative_survey_summary <- formative_survey %>% 
  summarize(`1`= mean(deaths_1month, na.rm = T), `1_se` =  sd(deaths_1month, na.rm = T) / sqrt(n()), 
            `3`= mean(deaths_3month, na.rm = T), `3_se` =  sd(deaths_3month, na.rm = T) / sqrt(n()),
            `6`= mean(deaths_6month, na.rm = T), `6_se` =  sd(deaths_6month, na.rm = T) / sqrt(n()), 
            `12` = mean(deaths_12month, na.rm = T), `12_se` =  sd(deaths_12month, na.rm = T) / sqrt(n())) %>% 
  mutate(id = 1) %>% 
  pivot_longer(-id)

formative_survey_summary <- formative_survey_summary %>% 
  pivot_wider(names_from = name, values_from = value) %>% 
  pivot_longer(-id) %>% 
  mutate(se = case_when(value < 0.5 ~ "standard_error",
                        TRUE ~ "mean")) %>%
  mutate(month = parse_number(name)) %>% 
  select(-name) %>% 
  pivot_wider(names_from = se, values_from = value) %>% 
  mutate(mean = mean / month,
         standard_error = standard_error / month) 

formative_survey_summary %>% 
  ggplot(aes(x = as.factor(month), y = mean, ymax = mean - 1.96 * standard_error, ymin = mean +  1.96 * standard_error)) + 
  geom_col(color = "black", fill = "grey") + 
  geom_errorbar(width = 0.2) + 
  geom_text(aes(x = as.factor(month), y = mean + 0.2, label = round(mean, 2))) + 
  cowplot::theme_cowplot() + 
  labs(x = "Observation Window Length (Months)",
       y = "Average Deaths Reported per Month")

```


```{r, echo = F}
## deaths 3 month 
deaths_plot <- formative_survey %>% 
  ggplot(aes(x = deaths_3month)) +
  geom_histogram(binwidth = 1, color = "black", fill = "grey") + 
  cowplot::theme_cowplot() + 
  labs(x = "Reported Deaths (3 Mo.)")

## talk weekly last 3 month 
denominator_plot <- formative_survey %>% 
  ggplot(aes(x = network_talk_weekly)) +
  geom_histogram(binwidth = 50, color = "black", fill = "grey") + 
  cowplot::theme_cowplot() + 
  labs(x = "Network Size (Talk weekly, 3 Mo.)")

## combined plot 
cowplot::plot_grid(deaths_plot, denominator_plot)
```

## correlation between deaths reported and network size 
```{r}
formative_survey %>%
  ggplot(aes(x = deaths_3month, y = network_talk_weekly)) + 
  geom_point(alpha = 0.5) + 
  cowplot::theme_cowplot() + 
  geom_smooth()

formative_survey %>% 
  summarize(cor(deaths_3month, network_talk_weekly))
```


```{r}
formative_survey %>% 
  mutate(gender = `0.1.o) Quel est le genre de l’IC ?`) %>% 
  group_by(gender) %>% 
  filter(network_talk_weekly < 200) %>% 
  summarize(count = mean(network_talk_weekly),
            se = sd(network_talk_weekly) / sqrt(n()),
            n = n()) %>% 
  ggplot(aes(x = gender,
             y = count,
             ymin = count - 1.96*se,
             ymax = count + 1.96*se)) + 
  geom_pointrange() + 
  cowplot::theme_cowplot() + 
  ylim(0, 50) + 
  labs(x = "gender",
       y = "Network Size",
       title = "Gender Difference in Network Size")
```


```{r}
formative_survey %>% 
  summarize(total = mean(network_talk_weekly, na.rm = T),
            infants = mean(infants, na.rm = T),
            community = mean(in_community, na.rm = T),
            infants_community = mean(infants_in_community, na.rm = T)) %>% 
  mutate(infants_prop = infants/total,
         infants_community_prop = infants_community / community)
```

```{r}
formative_survey %>% 
  summarize(total = mean(network_talk_weekly, na.rm = T),
            infants = mean(infants, na.rm = T),
            community = mean(in_community, na.rm = T),
            infants_community = mean(infants_in_community, na.rm = T)) %>% 
  mutate(infants_prop = infants/total,
         infants_community_prop = infants_community / community)
```



```{r}
formative_survey %>% 
  mutate(child_rate = infants/network_talk_weekly,
         child_community_rate = infants_in_community/in_community) %>% 
  summarize(child_rate_mean = mean(child_rate, na.rm = T),
            child_rate_se = sd(child_rate, na.rm = T) / sqrt(n()),
            child_community_rate_mean = mean(child_community_rate, na.rm = T),
            child_community_rate_se = sd(child_community_rate, na.rm = T) / sqrt(n()))


formative_survey %>% 
  drop_na(network_talk_weekly, in_community, infants, infants_in_community) %>% 
  summarize(total_connections = sum(network_talk_weekly),
         total_community_connections = sum(in_community),
         total_u5 = sum(infants),
         total_u5_community = sum(infants_in_community),
         n = n()) %>% 
  mutate(proportions_u5 = total_u5/total_connections,
         proportions_u5_community = total_u5_community/total_community_connections) %>% 
  select(`proportion U5` = proportions_u5, `proportion u5 (community)` = proportions_u5_community, n) %>% 
  pivot_longer(-n) %>% 
  mutate(sd = sqrt((value) * (1 - value)) / sqrt(n)) %>%  
  ggplot(aes(x = name,
             y = value, 
             ymin = value - 1.96*sd,
             ymax = value + 1.96*sd)) + 
  geom_pointrange() +
  cowplot::theme_cowplot() + 
  ylim(0, .4)
  
```

