---
title: "R Notebook"
output: html_notebook
---



```{r}
library(survey)
```


```{r}
networksurvival::generate_raking_weights(weighting_targets = weighting_raking_targets, survey_df = survey_df) 

margin_pop <- weighting_raking_targets %>%
  filter(health_zone == "Nyunzu") %>%
  filter(variable %in% c("wealth_score_categorical", "age_class", "gender", "hh_size_categorical_crude")) %>%
  #filter(variable != "wealth_score_categorical") %>% 
  select(-health_zone)

df_filtered <- survey_df %>%
      dplyr::filter(health_zone == "Nyunzu") %>%
      harvest(margin_pop, convergence = c(pct = 0.0000001, absolute = 1e-10), max_iterations = 100000, verbose = 2)


summary(df_filtered$weight)
```


```{r}
margin_pop_weird <- margin_pop %>%
  mutate(proportion = proportion * nrow(df_filtered)) %>% 
 # filter(variable != "hh_size_categorical_crude") %>% 
  pivot_wider(names_from = c(variable, level), values_from = proportion, names_sep = "") %>% 
  select(-`age_class[18,25)`, -genderf, -wealth_score_categorical0, -`hh_size_categorical_crude[0,6)`, wealth_score_categorical = wealth_score_categorical1)

named_vector <- setNames(as.numeric(margin_pop_weird[1, ]), names(margin_pop_weird))
```



```{r}
(test<-calibrate(df_filtered_survey, ~gender + age_class + wealth_score_categorical + hh_size_categorical_crude, c(`(Intercept)`=nrow(df_filtered), named_vector)))

calibrated_weights <- weights(test)

summary(calibrated_weights)
```




## model weights 


```{r}
df_filtered
```

```{r}
# Assume df is your dataframe with variables: selected (1 for selected, 0 for not), x1, x2, x3...

# Step 1: Fit a logistic regression model to estimate the probability of being selected
selection_model <- glm(selected ~ x1 + x2 + x3, data = df, family = "binomial")

# Step 2: Predict the selection probabilities
df$selection_prob <- predict(selection_model, type = "response")

# Step 3: Calculate the inverse probability weights
df$ipw <- 1 / df$selection_prob
```



```{r}
weighting_df <- survey_df %>% 
  filter(health_zone == "Nyunzu") %>% 
  select("hh_size_categorical", "hh_size_categorical_crude", "cooking_fuel",
         "material_house", "modern_fuel_type", "manufactured_material_house", "radio", "bed", "_id", "age_class", "gender", "age_u5_count", "age_5_18_count", "age_18plus_count") %>% 
  mutate(inclusion = 1) %>% 
  bind_rows(hh_weighting_df %>% 
                filter(health_zone == "Nyunzu") %>% 
              mutate(inclusion = 0)) 


# Step 1: Fit a logistic regression model to estimate the probability of being selected
selection_model <- glm(inclusion ~ gender*age_class + hh_size_categorical + radio + bed + material_house + modern_fuel_type + age_u5_count + age_5_18_count + age_18plus_count,  data = weighting_df, family = "binomial")

# Step 2: Predict the selection probabilities
survey_df_nyunzu <- survey_df %>% 
  filter(health_zone == "Nyunzu") %>% 
  mutate(selection_prob = predict(selection_model, survey_df %>% filter(health_zone == "Nyunzu"), type = "response")) %>% 
  mutate(ipw = 1 / selection_prob) %>% 
  mutate(weight_ipw = ipw / mean(ipw)) %>% 
   mutate(weight_ipw = case_when(
    weight_ipw > 10 ~ 10,
    TRUE ~ weight_ipw
  ))



survey_df <- survey_df %>% 
  mutate(weight_ipw = ipw / mean(ipw))  %>% 
  mutate(weight_ipw = case_when(
    weight_ipw > 10 ~ 10,
    TRUE ~ weight_ipw
  ))

ipw_weights <-  survey_df_nyunzu %>% 
  distinct(weight_ipw, uuid_ki)


death_df <- death_df %>% 
  filter(health_zone == "Nyunzu") %>% 
  inner_join(ipw_weights, by = "uuid_ki") 
```



```{r}
test <- (networksurvival::compute_cdr_comprehensive(death_df = death_df,
                                                                survey_df = survey_df_nyunzu,
                                                                weight_col = "weight_ipw",
                                                                bootstrap = NA,
                                                                monthly = F))
test
```

```{r}
## calculate cdr raking 
cdr_pooled_point_raking <- networksurvival::compute_cdr_comprehensive(death_df = quota_sample_deaths %>% filter(health_zone == "Nyunzu"),
                                                                  survey_df = quota_sample_survey %>% filter(health_zone == "Nyunzu"),
                                                                  weight_col = "weight_raking")
```

```{r}
lm(num_deaths_total ~ weight_ipw, data = survey_df_nyunzu)
```



```{r}
survey_df_nyunzu %>% 
  mutate(weight = case_when(
    weight_ipw < 1 ~ "<1",
    weight_ipw >= 1 & weight_ipw <= 2 ~ "1-2",
    weight_ipw >= 2 ~ "2+"
  )) %>%
  group_by(weight) %>% 
  summarize(num_deaths_total = mean(num_deaths_total, na.rm = T)) %>% 
  ggplot(aes(x = weight, y = num_deaths_total)) + 
  geom_point() + 
  theme_cowplot() + 
  labs(title = "Deaths by weight category", x = "Weight category", y = "Avg. Deaths Reported") + 
  ylim(0, 1.5)
```


