---
title: "Mortality Estimation"
---

```{r}
## library packages 
library(tidyverse)
library(data.table)
library(gt)
library(here)
library(cowplot)

## read in data 
survey_df <- read_csv(here("data/clean_data/casey_files/weight_survey.csv")) %>% 
  mutate(start_month = lubridate::floor_date(x = as_date(start), unit = "month"))
death_df <- read_csv(here("data/clean_data/casey_files/deaths_weighted.csv")) %>% 
  mutate(uuid_ki = uuid_ki4) %>% 
  mutate(zone_de_sante_name = case_when(
      death_zs == 746101 ~ "Kalemie",           
      death_zs == 746601 ~ "Nyunzu",            
      death_zs == 746102 ~ "Nyemba"))          
```

## Estimate exposure for neighbors 

```{r}
survey_df %>% 
  count(month = lubridate::floor_date(x = as_date(start), unit = "month"))

exposure <- survey_df  %>% 
  summarize(exp_jan = lubridate::interval(as_date("2023-01-01"), pmin(as_date("2023-02-01"), as_date(start))) %/% days(1) * num_total_neighbour * weights,
            exp_feb = lubridate::interval(as_date("2023-02-01"), pmin(as_date("2023-03-01"), as_date(start))) %/% days(1) * num_total_neighbour * weights,
            exp_mar = lubridate::interval(as_date("2023-03-01"), pmin(as_date("2023-04-01"), as_date(start))) %/% days(1) * num_total_neighbour * weights,
            exp_apr = lubridate::interval(as_date("2023-04-01"), pmin(as_date("2023-05-01"), as_date(start))) %/% days(1) * num_total_neighbour * weights,
            exp_may = lubridate::interval(as_date("2023-05-01"), pmin(as_date("2023-06-01"), as_date(start))) %/% days(1) * num_total_neighbour * weights,
            exp_jun = lubridate::interval(as_date("2023-06-01"), pmin(as_date("2023-07-01"), as_date(start))) %/% days(1) * num_total_neighbour * weights)

exposure_monthly_neighbor <- exposure %>% 
  mutate(across(colnames(exposure), ~pmax(0, .x))) %>% 
  summarize(across(colnames(exposure), ~sum(.x, na.rm = T)))
  # mutate(monthly_exposure_apr = pmax(0, monthly_exposure_apr))

exposure_monthly_neighbor_long <- exposure_monthly_neighbor %>% 
  mutate(id = 1) %>% 
  pivot_longer(-id)

neighbor_results <- death_df %>% 
  filter(`death_relationship/neighbour` == 1) %>% 
  mutate(death_month = lubridate::floor_date(x = as_date(date_join_final_death), unit = "month")) %>% 
  group_by(death_month) %>% 
  summarize(n = sum(weights), n_unweighted = n()) %>% 
  filter(!is.na(death_month)) %>% 
  bind_cols(exposure_monthly_neighbor_long) %>% 
  mutate(death_rate = 10000 * n / value)
```



```{r}
## Exposure Kin 
exposure_kin <- survey_df  %>% 
  summarize(exp_jan = lubridate::interval(as_date("2023-01-01"), pmin(as_date("2023-02-01"), as_date(start))) %/% days(1) * num_total_kin * weights,
            exp_feb = lubridate::interval(as_date("2023-02-01"), pmin(as_date("2023-03-01"), as_date(start))) %/% days(1) * num_total_kin * weights,
            exp_mar = lubridate::interval(as_date("2023-03-01"), pmin(as_date("2023-04-01"), as_date(start))) %/% days(1) * num_total_kin * weights,
            exp_apr = lubridate::interval(as_date("2023-04-01"), pmin(as_date("2023-05-01"), as_date(start))) %/% days(1) * num_total_kin * weights,
            exp_may = lubridate::interval(as_date("2023-05-01"), pmin(as_date("2023-06-01"), as_date(start))) %/% days(1) * num_total_kin * weights,
            exp_jun = lubridate::interval(as_date("2023-06-01"), pmin(as_date("2023-07-01"), as_date(start))) %/% days(1) * num_total_kin * weights)

exposure_monthly_kin <- exposure_kin %>% 
  mutate(across(colnames(exposure), ~pmax(0, .x))) %>% 
  summarize(across(colnames(exposure), ~sum(.x, na.rm = T)))
  # mutate(monthly_exposure_apr = pmax(0, monthly_exposure_apr))

exposure_monthly_kin_long <- exposure_monthly_kin %>% 
  mutate(id = 1) %>% 
  pivot_longer(-id)

exposure_monthly_kin_long %>% 
  ggplot(aes(x = reorder(name, -value), y = value )) + 
  geom_col() + 
  cowplot::theme_cowplot() + 
  labs(x = "Month", y = "Value")

death_df %>% 
  filter(`death_relationship/neighbour` == 0) %>% 
  mutate(death_month = lubridate::floor_date(x = as_date(date_join_final_death), unit = "month")) %>% 
  group_by(death_month) %>% 
  summarize(n = sum(weights), n_unweighted = n()) %>% 
  filter(!is.na(death_month)) %>% 
  bind_cols(exposure_monthly_kin_long) %>% 
  mutate(death_rate = 10000 * n / value) %>% 
  mutate(estimate = "kin")
```


```{r}
calculate_exposure_and_death_kin <- function(death_df, survey_df, bootstrap = NA) {
  
  results_list <- list()
  
  if (is.na(bootstrap)) {
    # No bootstrapping, just run the main code once
    results_list[[1]] <- estimate_mortality_kin(death_df, survey_df)
  } else {
    
    # Run the main code 'bootstrap' times
    for (i in 1:bootstrap) {
      
    ## bootstrap resample 
      boot_survey_df <- survey_df %>% 
        group_by(zone_de_sante_name, gender, start_month) %>% 
        sample_n(size = n(), replace = T) %>% 
        ungroup()
      
      # Filter death_df to match the unique_ids in boot_survey_df, with appropriate repetition
      # Count occurrences of each unique_id in boot_survey_df
      count_ids <- boot_survey_df %>% 
        count(uuid_ki)
      
      # Replicate rows of boot_death_df_final based on count_ids
      boot_death_df_final <- death_df %>%
        inner_join(count_ids, by = c("uuid_ki")) %>%
        slice(rep(1:n(), each = n))
      
      results_list[[i]] <- estimate_mortality_kin(survey_df = boot_survey_df, death_df = boot_death_df_final) %>% 
    mutate(bootstrap_iter = i)
      cat(i)
    }
  }
  return(results_list)
}

estimate_mortality_kin <- function(death_df, survey_df) {
  
  # Exposure Kin
  exposure_kin <- survey_df  %>% 
    summarize(
       `2023-01-01` = lubridate::interval(as_date("2023-01-01"), pmin(as_date("2023-02-01"), as_date(start))) %/% days(1) * num_total_kin * weights,
       `2023-02-01` = lubridate::interval(as_date("2023-02-01"), pmin(as_date("2023-03-01"), as_date(start))) %/% days(1) * num_total_kin * weights,
       `2023-03-01` = lubridate::interval(as_date("2023-03-01"), pmin(as_date("2023-04-01"), as_date(start))) %/% days(1) * num_total_kin * weights,
       `2023-04-01` = lubridate::interval(as_date("2023-04-01"), pmin(as_date("2023-05-01"), as_date(start))) %/% days(1) * num_total_kin * weights,
       `2023-05-01` = lubridate::interval(as_date("2023-05-01"), pmin(as_date("2023-06-01"), as_date(start))) %/% days(1) * num_total_kin * weights,
       `2023-06-01` = lubridate::interval(as_date("2023-06-01"), pmin(as_date("2023-07-01"), as_date(start))) %/% days(1) * num_total_kin * weights
    ) 
  
  exposure_monthly_kin <- exposure_kin %>% 
    mutate(across(colnames(.), ~pmax(0, .x))) %>% 
    summarize(across(colnames(.), ~sum(.x, na.rm = T)))
  
  exposure_monthly_long <- exposure_monthly_kin %>% 
    mutate(id = 1) %>% 
    pivot_longer(-id) %>% 
    mutate(month = lubridate::as_date(name))
  
  death_count <- death_df %>% 
    filter(`death_relationship/neighbour` == 0) %>% 
    mutate(death_month = lubridate::floor_date(x = as_date(date_join_final_death), unit = "month")) %>% 
    group_by(death_month) %>% 
    summarize(n = sum(weights), n_unweighted = n()) %>% 
    filter(!is.na(death_month)) 
  
  results_df <- exposure_monthly_long %>% 
    # left_join(death_count, by = c("month" = "death_month")) %>% 
    mutate(death_rate = 10000 * n / value) 
  
  return(results_df)
}

calculate_exposure_and_death_kin(death_df, survey_df, bootstrap = NA) 
```


```{r}
calculate_exposure_and_death_neighbor <- function(death_df, survey_df, bootstrap = NA) {
  
  results_list <- list()
  
  if (is.na(bootstrap)) {
    # No bootstrapping, just run the main code once
    results_list[[1]] <- estimate_mortality_neighbor(death_df, survey_df)
  } else {
    
    # Run the main code 'bootstrap' times
    for (i in 1:bootstrap) {

        boot_survey_df <- survey_df %>% 
        group_by(zone_de_sante_name, gender, start_month) %>% 
        sample_n(size = n(), replace = T) %>% 
        ungroup()
      
      # Filter death_df to match the unique_ids in boot_survey_df, with appropriate repetition
      # Count occurrences of each unique_id in boot_survey_df
      count_ids <- boot_survey_df %>% 
        count(uuid_ki)
      
      # Replicate rows of boot_death_df_final based on count_ids
      boot_death_df_final <- death_df %>%
        inner_join(count_ids, by = "uuid_ki") %>%
        ungroup() %>%
        slice(rep(row_number(), count_ids$n))
      
      results_list[[i]] <- estimate_mortality_neighbor(survey_df = boot_survey_df, death_df = boot_death_df_final) %>% 
    mutate(bootstrap_iter = i)
      cat(i)
    }
  }
  return(results_list)
}

estimate_mortality_neighbor <- function(death_df, survey_df) {
  
  # Exposure Kin
  exposure_neighbor <- survey_df  %>% 
    summarize(
      `2023-01-01` = lubridate::interval(as_date("2023-01-01"), pmin(as_date("2023-02-01"), as_date(start))) %/% days(1) * num_total_hh_neighbour * weights,
      `2023-02-01` = lubridate::interval(as_date("2023-02-01"), pmin(as_date("2023-03-01"), as_date(start))) %/% days(1) * num_total_hh_neighbour * weights,
      `2023-03-01` = lubridate::interval(as_date("2023-03-01"), pmin(as_date("2023-04-01"), as_date(start))) %/% days(1) * num_total_hh_neighbour * weights,
      `2023-04-01` = lubridate::interval(as_date("2023-04-01"), pmin(as_date("2023-05-01"), as_date(start))) %/% days(1) * num_total_hh_neighbour * weights,
      `2023-05-01` = lubridate::interval(as_date("2023-05-01"), pmin(as_date("2023-06-01"), as_date(start))) %/% days(1) * num_total_hh_neighbour * weights,
      `2023-06-01` = lubridate::interval(as_date("2023-06-01"), pmin(as_date("2023-07-01"), as_date(start))) %/% days(1) * num_total_hh_neighbour * weights
    ) 
  
  exposure_monthly_neighbor <- exposure_neighbor %>% 
    mutate(across(colnames(.), ~pmax(0, .x))) %>% 
    summarize(across(colnames(.), ~sum(.x, na.rm = T)))
  
  exposure_monthly_long <- exposure_monthly_neighbor %>% 
    mutate(id = 1) %>% 
    pivot_longer(-id) %>% 
    mutate(month = lubridate::as_date(name))
  
  ## monthly estimates 
  # death_count <- death_df %>% 
  #   filter(`death_relationship/neighbour` == 1 | `death_relationship/household` == 1) %>% 
  #   mutate(death_month = lubridate::floor_date(x = as_date(date_join_final_death), unit = "month")) %>% 
  #   group_by(death_month) %>% 
  #   summarize(n = sum(weights), n_unweighted = n()) %>% 
  #   filter(!is.na(death_month)) 
  
  death_count <- death_df %>% 
    filter(`death_relationship/neighbour` == 1 | `death_relationship/household` == 1) %>% 
    summarize(n = sum(weights), n_unweighted = n()) 
  
  results_df <- exposure_monthly_long %>% 
    left_join(death_count, by = c("month" = "death_month")) %>% 
    mutate(death_rate = 10000 * n / value) 
  
  return(results_df)
}
```


```{r}
funcs <- c("calculate_exposure_and_death_neighbor", "calculate_exposure_and_death_kin")
results_list <- list()

for (func_name in funcs) {
  func_to_call <- get(func_name)
  temp_result <- func_to_call(
    death_df,
    survey_df,
    bootstrap = 100
  ) %>%
    bind_rows() %>%
    group_by(bootstrap_iter) %>% 
    summarize(rate = sum(n, na.rm = TRUE) * 10000 / sum(value, na.rm = TRUE),
              method = func_name)
                
  results_list[[length(results_list) + 1]] <- temp_result
}

final_result <- bind_rows(results_list)

```



```{r}
kin_bootstrap <- calculate_exposure_and_death_kin(death_df, survey_df, bootstrap = 300) 

kin_results <- bind_rows(kin_bootstrap) 

neighbor_bootstrap <- calculate_exposure_and_death_neighbor(death_df, survey_df, bootstrap = 1000)

neighbor_results <- bind_rows(neighbor_bootstrap)
```


```{r}
kin_results <- kin_results %>% 
  group_by(month) %>% 
  summarize(lower = quantile(death_rate, 0.025),
            upper = quantile(death_rate, 0.975),
            mean = mean(death_rate)) %>% 
  mutate(network = "kin")

neighbor_results <- neighbor_results %>% 
  group_by(month) %>% 
  summarize(lower = quantile(death_rate, 0.025, na.rm = T),
            upper = quantile(death_rate, 0.975, na.rm = T),
            mean = mean(death_rate)) %>% 
  mutate(network = "neighbor")

monthly_results <- neighbor_results %>% 
  bind_rows(kin_results) %>% 
  filter(month != as_date("2023-06-01")) %>% 
  ggplot(aes(x = month, color = network, shape = network, y = mean, ymin = lower, ymax = upper)) + 
  geom_pointrange( position = position_dodge(5), size = .75, fill = "white") +
  geom_line(linetype = "dashed", alpha = 0.3) + 
  scale_shape_manual(values = c(21, 23)) +
  ggsci::scale_color_lancet() + 
  ylim(0, 1.5) + 
  # geom_hline(yintercept = 1, linetype = "dashed") + 
  theme_cowplot() + 
  theme(legend.position = "bottom") + 
  labs(x = "Month of Death", y = "Crude Death Rate")

ggsave(plot = monthly_results, filename = here("figures/main_plot_monthly.png"), width = 7, height = 5)
```





## Estimate mortality for each ZS

```{r}
zones <- c("Nyemba", "Nyunzu", "Kalemie")
funcs <- c("calculate_exposure_and_death_neighbor", "calculate_exposure_and_death_kin")
results_list <- list()

for (zone in zones) {
  for (func_name in funcs) {
    func_to_call <- get(func_name)
    temp_result <- func_to_call(
      death_df %>% filter(zone_de_sante_name == zone),
      survey_df %>% filter(zone_de_sante_name == zone),
      bootstrap = 100
    ) %>%
      bind_rows() %>%
      group_by(bootstrap_iter) %>% 
      summarize(rate = sum(n, na.rm = T) * 10000 / sum(value, na.rm = T),
                zone_de_sante_name = zone,
                method = func_name) 
                
    results_list[[length(results_list) + 1]] <- temp_result
  }
}

final_result <- bind_rows(results_list)

```

```{r}
zone_de_sante <- final_result %>% 
  mutate(method = case_when(
    method == "calculate_exposure_and_death_neighbor" ~ "Neighbor",
    method == "calculate_exposure_and_death_kin" ~ "Kin"
  )) %>% 
  group_by(zone_de_sante_name, method) %>% 
  summarize(lower = quantile(rate, 0.025),
            upper = quantile(rate, 0.975),
            mean = mean(rate))

zone_de_sante_plot <- zone_de_sante %>% 
  ggplot(aes(x = zone_de_sante_name, color = method, shape = method, y = mean, ymin = lower, ymax = upper)) + 
  geom_pointrange( position = position_dodge(.1), size = .75, fill = "white") +
  scale_shape_manual(values = c(21, 23)) +
  ggsci::scale_color_lancet() + 
  ylim(0, 1.2) + 
  theme_cowplot() + 
  theme(legend.position = "bottom") + 
  labs(x = "Zone de Sante", y = "Daily Crude Death Rate")

ggsave(plot = zone_de_sante_plot, filename = here("figures/main_plot_zs.png"), width = 6, height = 4)
```




```{r}
overall_estimate <- final_result %>% 
  mutate(method = case_when(
    method == "calculate_exposure_and_death_neighbor" ~ "Neighbor",
    method == "calculate_exposure_and_death_kin" ~ "Kin"
  )) %>% 
  group_by(method) %>% 
  summarize(lower = quantile(rate, 0.025),
            upper = quantile(rate, 0.975),
            mean = mean(rate))

# overall_estimate <- overall_estimate %>% 
#   add_row(method = "2022 HH Survey",
#           lower = 0.34,
#           upper = 0.98,
#           mean = 0.58)

main_estimate_plot <- overall_estimate %>% 
  ggplot(aes(x = method, color = method, shape = method, y = mean, ymin = lower, ymax = upper)) + 
  geom_pointrange( position = position_dodge(.1), size = .75, fill = "white") +
  scale_shape_manual(values = c(21, 23)) +
  ggsci::scale_color_lancet() + 
  ylim(0, 1.5) + 
  theme_cowplot() + 
  theme(legend.position = "bottom") + 
  labs(x = "Network Tie", y = "Crude Death Rate") 


main_estimate_plot_plus_emerg_mort <- overall_estimate %>% 
  ggplot(aes(x = method, color = method, shape = method, y = mean, ymin = lower, ymax = upper)) + 
  geom_pointrange( position = position_dodge(.1), size = .75, fill = "white") +
  scale_shape_manual(values = c(21, 23)) +
  ggsci::scale_color_lancet() + 
  ylim(0, 1.5) + 
  theme_cowplot() + 
  theme(legend.position = "bottom") + 
  geom_hline(yintercept = 1, linetype = "dashed") + 
  labs(x = "Network Tie", y = "Crude Death Rate") 

ggsave(plot = main_estimate_plot, filename = here("figures/main_plot.png"), width = 6, height = 4)
ggsave(plot = main_estimate_plot_plus_emerg_mort, filename = here("figures/main_plot2.png"), width = 6, height = 4)

```

