---
title: "Presentation - Oxford Hard-To-Reach"
author: "Casey Breen"
---

Summary: Preliminary exploration of DRC Data 


```{r}
library(tidyverse)
library(data.table)
library(gt)
library(xtable)
library(cowplot)
library(here)
```


```{r}
## read in data 
survey_df <- read_csv(here("data/clean_data/casey_files/weight_survey.csv"))
death_df <- read_csv(here("data/clean_data/casey_files/deaths_weighted.csv")) %>% 
  mutate(uuid_ki = uuid_ki4) %>% 
  mutate(zone_de_sante_name = case_when(
      death_zs == 746101 ~ "Kalemie",           
      death_zs == 746601 ~ "Nyunzu",            
      death_zs == 746102 ~ "Nyemba"))  
```

## Interviews per region per month 

```{r}
interviews <- survey_df %>% 
  mutate(month = lubridate::floor_date(x = as_date(start), unit = "month")) %>% 
  filter(!is.na(month)) %>% 
  group_by(month, zone_de_sante_name) %>% 
  count() %>% 
  filter(!is.na(zone_de_sante_name)) %>% 
  pivot_wider(names_from = zone_de_sante_name, values_from = n) 


print(xtable(interviews, type = "latex"), file = "filename2.tex")

```

## 

```{r}
death_df %>% 
  mutate(death_month = lubridate::floor_date(x = as_date(date_join_final_death), unit = "month")) %>% 
  mutate(report_month = lubridate::floor_date(x = as_date(death_date_dc), unit = "month")) %>% 
  filter(report_month != as_date("2023-02-01")) %>% ## filter out February interviews  
  filter(!is.na(death_month)) %>% 
  ggplot(aes(x = death_month )) + 
  geom_histogram(binwidth = 10) + 
  facet_wrap(~report_month) + 
  cowplot::theme_cowplot() 
```
## Deaths Histogram

```{r}
kin_deaths <- survey_df %>% 
  count(num_deaths_kin) %>% 
  filter(!is.na(num_deaths_kin)) %>% 
  rename(deaths = num_deaths_kin) %>% 
  mutate(type = "Reported kin deaths")

neighbor_deaths <- survey_df %>% 
  count(num_deaths_neighbours) %>% 
  filter(!is.na(num_deaths_neighbours)) %>%
  rename(deaths = num_deaths_neighbours) %>% 
  mutate(type = "Reported neighbor deaths")

plot_deaths <- bind_rows(kin_deaths, neighbor_deaths) %>% 
  ggplot(aes(x = deaths, y = n)) + 
  geom_col(color= "black", fill = "grey") + 
  facet_wrap(~type) + 
  theme_cowplot()

```

## Network size histogram 

```{r}
kin_denom <- survey_df %>% 
  count(num_total_kin) %>% 
  filter(!is.na(num_total_kin)) %>% 
  rename(size = num_total_kin) %>% 
  mutate(type = "Kin degree (mean = 27)")

neighbor_denom <- survey_df %>% 
  count(num_total_neighbour) %>% 
  filter(!is.na(num_total_neighbour)) %>%
  rename(size = num_total_neighbour) %>% 
  mutate(type = "Neighbor degree (mean = 29)")

plot_denom <- bind_rows(kin_denom, neighbor_denom) %>% 
  ggplot(aes(x = size, y = n)) + 
  geom_col(color= "black", fill = "grey") + 
  facet_wrap(~type) + 
  theme_cowplot()

```

```{r}
combined_plot <- cowplot::plot_grid(plot_deaths, plot_denom, zone_de_sante_plot, labels = "AUTO", nrow = 3)

ggsave(plot = combined_plot, filename = here("figures/combined_plot.png"), height = 12, width = 8)
```



```{r}
survey_df %>% 
  select(sex, age_class, zone_de_sante_name) %>% 
  group_by(zone_de_sante_name) %>% 
  count(sex, age_class) %>% 
  mutate(prop = n / sum(n)) %>% 
  pivot_wider(names_from = "zone_de_sante_name", values_from = "prop")
```

```{r}
# Calculate n and percentages
table <- survey_df %>%
  select(sex, age_class, zone_de_sante_name) %>%
  group_by(zone_de_sante_name, age_class, sex) %>%
  summarise(n = n()) %>%
  group_by(zone_de_sante_name) %>%
  mutate(total = sum(n)) %>%
  ungroup() %>%
  mutate(perc = (n / total) * 100) %>%
  select(-total) %>%
  pivot_wider(names_from = zone_de_sante_name, values_from = c(n, perc))

# Generate LaTeX table
latex_code <- xtable(table, caption="Survey Data by Zone de Sante, Age Class, and Sex", label="table:survey")
print(latex_code, type="latex", caption.placement="top")
```

