---
title: "reference_periosds"
format: html
editor: visual
---

## Quarto

```{r}
library(tidyverse)
library(here)
library(lubridate)
```

```{r}
## read in data
observation_window <- readxl::read_excel(here("data/observation_window.xlsx"))

## visualize
observation_window %>%
  ggplot(aes(x = interview_date, y = observation_period_length)) +
  geom_point() +
  geom_line() +
  cowplot::theme_cowplot() +
  ylim(0, 150) +
  geom_vline(aes(xintercept = date), linetype = "dashed")
```

```{r}
## results wave 2
results_2 <- list()

## geom ridges
for (wave in 1:3) {
  results <- list()

  for (i in 1:10000) {
    results[[i]] <- tibble(estimate = mean(rbinom(n = 200, prob = .33, size = 1)) / mean(rnorm(n = 600, sd = 20, mean = 50)) * 10000 / 75, iteration = i)
  }

  results_2 <- bind_rows(results) %>%
    mutate(wave_index = wave)
}

results <- bind_rows(results_2)

ggplot(data = results, aes(x = wave, y = estimate)) +
  ggridges::geom_density_ridges()
```

```{r}
test1 <- test
test2 <- test
test3 <- test
```

```{r}
bind_rows(
  test1 %>% mutate(round = 1),
  test2 %>% mutate(round = 2),
  test3 %>% mutate(round = 3)
) %>%
  ggplot() +
  geom_pointrange(aes(x = sample, y = mean, ymin = low, ymax = upper)) +
  cowplot::theme_cowplot() +
  ylim(0, 1.3)
```
